import type { ItemResponseDto } from './item.dto';

export const MOCK_WEAPONS_ITEMS: ItemResponseDto[] = [
  {
    id: '500',
    name: 'Bistouri',
    image: '/assets/items/Bistouri70.webp',
    tech: 60,
    integrity: 100,
    type: '2handsMelee',
    prerequisites: [
      {
        property: 'medicine',
        value: 150,
      },
    ],
    effects: [
      {
        property: 'medicine',
        value: 10,
      },
    ],
    minDamage: 4,
    maxDamage: 12,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '501',
    name: 'Dague énergétique',
    image: '/assets/items/DAGUE_ENERGETIQUE262.webp',
    tech: 350,
    integrity: 150,
    type: '1handMelee',
    effects: [
      {
        property: 'agility',
        value: 10,
      },
    ],
    minDamage: 20,
    maxDamage: 30,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '502',
    name: 'Kanuf',
    image: '/assets/items/KANUF_262px.webp',
    tech: 300,
    integrity: 50,
    type: '1handMelee',
    effects: [
      {
        property: 'agility',
        value: 5,
      },
    ],
    minDamage: 24,
    maxDamage: 32,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '503',
    name: 'Poing américain',
    image: '/assets/items/Poing_americain.webp',
    tech: 120,
    integrity: 200,
    type: '1handMelee',
    effects: [
      {
        property: 'strength',
        value: 5,
      },
    ],
    minDamage: 20,
    maxDamage: 38,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '504',
    name: 'Gants Cyber',
    image: '/assets/items/Gants_bijou.webp',
    tech: 240,
    integrity: 300,
    type: '2handsMelee',
    prerequisites: [
      {
        property: 'strength',
        value: 50,
      },
    ],
    effects: [
      {
        property: 'strength',
        value: 5,
      },
    ],
    minDamage: 38,
    maxDamage: 70,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '505',
    name: 'Gants de boxe',
    image: '/assets/items/Gant_boxe.webp',
    tech: 0,
    integrity: 300,
    type: '2handsMelee',
    effects: [
      {
        property: 'agility',
        value: 20,
      },
    ],
    minDamage: 3,
    maxDamage: 7,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '506',
    name: 'Gant Hydro',
    image: '/assets/items/GANTS_HYDRO262.webp',
    tech: 240,
    integrity: 120,
    type: '1handMelee',
    effects: [
      {
        property: 'strength',
        value: 8,
      },
    ],
    minDamage: 16,
    maxDamage: 36,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '507',
    name: 'Gants à piques',
    image: '/assets/items/Gant-a-pik.webp',
    tech: 300,
    integrity: 250,
    type: '2handsMelee',
    prerequisites: [
      {
        property: 'strength',
        value: 50,
      },
    ],
    effects: [
      {
        property: 'strength',
        value: 5,
      },
    ],
    minDamage: 38,
    maxDamage: 64,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '508',
    name: 'Gants en cuir',
    image: '/assets/items/Cuirgants.webp',
    tech: 360,
    integrity: 80,
    type: '2handsMelee',
    effects: [
      {
        property: 'stealth',
        value: 15,
      },
    ],
    minDamage: 2,
    maxDamage: 6,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '509',
    name: 'Gants technologiques',
    image: '/assets/items/Gant-info999.webp',
    tech: 60,
    integrity: 100,
    type: '2handsMelee',
    prerequisites: [
      {
        property: 'computing',
        value: 150,
      },
      {
        property: 'agility',
        value: 130,
      },
    ],
    effects: [
      {
        property: 'computing',
        value: 10,
      },
    ],
    minDamage: 2,
    maxDamage: 6,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '510',
    name: 'Wolfers',
    image: '/assets/items/WOLFERS262.webp',
    tech: 300,
    integrity: 160,
    type: '2handsMelee',
    effects: [
      {
        property: 'agility',
        value: 10,
      },
    ],
    minDamage: 22,
    maxDamage: 78,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '511',
    name: 'Exo gants',
    image: '/assets/items/Exosquelette-main.webp',
    tech: 80,
    integrity: 150,
    type: '2handsMelee',
    prerequisites: [
      {
        property: 'engineering',
        value: 150,
      },
    ],
    effects: [
      {
        property: 'engineering',
        value: 10,
      },
    ],
    minDamage: 38,
    maxDamage: 68,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '512',
    name: 'Gantelet du Juge',
    image: '/assets/items/Gantlet_bleu.webp',
    tech: 320,
    integrity: 240,
    type: '2handsMelee',
    effects: [
      {
        property: 'strength',
        value: 15,
      },
    ],
    minDamage: 18,
    maxDamage: 38,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '513',
    name: 'Gantelet Steak',
    image: '/assets/items/Gants_steak.webp',
    tech: 60,
    integrity: 60,
    type: '2handsMelee',
    prerequisites: [
      {
        property: 'agility',
        value: 75,
      },
      {
        property: 'stealth',
        value: 75,
      },
    ],
    effects: [
      {
        property: 'stealth',
        value: 17,
      },
    ],
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '514',
    name: 'Gantelet A323',
    image: '/assets/items/Gant_A323.webp',
    tech: 360,
    integrity: 300,
    type: '1handMelee',
    minDamage: 21,
    maxDamage: 31,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '515',
    name: 'Gantelet AXXXN',
    image: '/assets/items/Gants_A-S9.webp',
    tech: 460,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '516',
    name: 'Gantelet AXXXP',
    image: '/assets/items/Gants_A-S9.webp',
    tech: 60,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'robustness',
        value: 40,
      },
      {
        property: 'speed',
        value: -2,
      },
    ],
  },
  {
    id: '517',
    name: 'Gantelet AXXXT',
    image: '/assets/items/Gants_A-S9.webp',
    tech: 60,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'perception',
        value: 40,
      },
    ],
  },
  {
    id: '518',
    name: 'Gantelet AXXXL',
    image: '/assets/items/Gants_A-S9.webp',
    tech: 60,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'stealth',
        value: 17,
      },
    ],
  },
  {
    id: '519',
    name: 'Gantelet AXXXJ',
    image: '/assets/items/Gants_A-S9.webp',
    tech: 60,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'engineering',
        value: 10,
      },
    ],
  },
  {
    id: '520',
    name: 'Gantelet AXXXO',
    image: '/assets/items/Gants_A-S9.webp',
    tech: 60,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'medicine',
        value: 10,
      },
    ],
  },
  {
    id: '521',
    name: 'Gantelet AXXXD',
    image: '/assets/items/Gants_A-S9.webp',
    tech: 60,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'computing',
        value: 10,
      },
    ],
  },
  {
    id: '522',
    name: 'Agrimensor',
    image: '/assets/items/AGRI2.webp',
    tech: 0,
    integrity: 120,
    type: '2handsMelee',
    minDamage: 50,
    maxDamage: 90,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 160,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -10,
      },
    ],
  },
  {
    id: '523',
    name: 'Epée à deux mains',
    image: '/assets/items/Epee_2m.webp',
    tech: 0,
    integrity: 120,
    type: '2handsMelee',
    minDamage: 55,
    maxDamage: 87,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 160,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -10,
      },
    ],
  },
  {
    id: '524',
    name: 'Epée énergétique',
    image: '/assets/items/Powersword.webp',
    tech: 100,
    integrity: 180,
    type: '2handsMelee',
    minDamage: 40,
    maxDamage: 78,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 80,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: 5,
      },
    ],
  },
  {
    id: '525',
    name: 'Epée quantique',
    image: '/assets/items/Epee_quantique.webp',
    tech: 320,
    integrity: 200,
    type: '2handsMelee',
    minDamage: 40,
    maxDamage: 78,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 80,
      },
    ],
    effects: [
      {
        property: 'strength',
        value: -10,
      },
    ],
  },
  {
    id: '526',
    name: 'Katana',
    image: '/assets/items/KATANNA_262px.webp',
    tech: 320,
    integrity: 140,
    type: '1handMelee',
    minDamage: 14,
    maxDamage: 36,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 120,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: 5,
      },
    ],
  },
  {
    id: '527',
    name: 'Tranchoir à fusion',
    image: '/assets/items/Tranchoir_fusion.webp',
    tech: 200,
    integrity: 130,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 90,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 150,
      },
      {
        property: 'engineering',
        value: 110,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -5,
      },
    ],
  },
  {
    id: '528',
    name: 'Lame carbone A370',
    image: '/assets/items/Lame-A370.webp',
    tech: 0,
    integrity: 200,
    type: '2handsMelee',
    minDamage: 50,
    maxDamage: 90,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'agility',
        value: -10,
      },
    ],
  },
  {
    id: '529',
    name: 'Blizzaxe',
    image: '/assets/items/Hacheglace.webp',
    tech: 180,
    integrity: 120,
    type: '2handsMelee',
    minDamage: 50,
    maxDamage: 78,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 120,
      },
      {
        property: 'agility',
        value: 110,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -5,
      },
    ],
  },
  {
    id: '530',
    name: 'Hache rustique',
    image: '/assets/items/Hache_rustique.webp',
    tech: 240,
    integrity: 160,
    type: '1handMelee',
    minDamage: 22,
    maxDamage: 34,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 60,
      },
      {
        property: 'agility',
        value: 120,
      },
    ],
  },
  {
    id: '531',
    name: 'Koup Koup',
    image: '/assets/items/Koup_koup.webp',
    tech: 180,
    integrity: 160,
    type: '2handsMelee',
    minDamage: 44,
    maxDamage: 84,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 160,
      },
      {
        property: 'agility',
        value: 110,
      },
    ],
  },
  {
    id: '532',
    name: 'Bouclier',
    image: '/assets/items/Bouclier.webp',
    tech: 0,
    integrity: 250,
    type: '1handMelee',
    minDamage: 13,
    maxDamage: 23,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 150,
      },
    ],
    effects: [
      {
        property: 'robustness',
        value: 20,
      },
      {
        property: 'speed',
        value: -1,
      },
    ],
  },
  {
    id: '533',
    name: 'Bouclier énergétique',
    image: '/assets/items/Powerbouclier.webp',
    tech: 0,
    integrity: 120,
    type: '1handMelee',
    minDamage: 20,
    maxDamage: 30,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    effects: [
      {
        property: 'robustness',
        value: 10,
      },
    ],
  },
  {
    id: '534',
    name: 'Batte de dreadball',
    image: '/assets/items/BATTE-DE-BASEBALL262.webp',
    tech: 80,
    integrity: 450,
    type: '1handMelee',
    minDamage: 24,
    maxDamage: 34,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '535',
    name: 'Batte de dreadball cloutée',
    image: '/assets/items/Batte-a-clou.webp',
    tech: 120,
    integrity: 400,
    type: '1handMelee',
    minDamage: 10,
    maxDamage: 26,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '536',
    name: 'Fouet',
    image: '/assets/items/Fouet.webp',
    tech: 320,
    integrity: 140,
    type: '1handMelee',
    minDamage: 20,
    maxDamage: 32,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 130,
      },
    ],
  },
  {
    id: '537',
    name: 'Hallebarde',
    image: '/assets/items/Hallebarde.webp',
    tech: 0,
    integrity: 200,
    type: '2handsMelee',
    minDamage: 48,
    maxDamage: 86,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 120,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -7,
      },
    ],
  },
  {
    id: '538',
    name: 'Masse énergétique',
    image: '/assets/items/Masse_energetique.webp',
    tech: 320,
    integrity: 320,
    type: '2handsMelee',
    minDamage: 52,
    maxDamage: 84,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'agility',
        value: -20,
      },
    ],
  },
  {
    id: '539',
    name: 'Monofilament',
    image: '/assets/items/MONOFILAMENT262.webp',
    tech: 240,
    integrity: 240,
    type: '2handsMelee',
    minDamage: 1,
    maxDamage: 99,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '540',
    name: 'Petite cuillère de la destruction',
    image: '/assets/items/Petite_cuillere.webp',
    tech: 0,
    integrity: 9999,
    type: '2handsMelee',
    minDamage: 99,
    maxDamage: 999,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '541',
    name: 'Pied de biche',
    image: '/assets/items/Pied_biche.webp',
    tech: 0,
    integrity: 250,
    type: '1handMelee',
    minDamage: 14,
    maxDamage: 48,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 50,
      },
      {
        property: 'agility',
        value: 50,
      },
    ],
  },
  {
    id: '542',
    name: 'Rouleau en poly tétra fluoro éthylène',
    image:
      '/assets/items/ROULEAU-PATISSERIE_262px.webp',
    tech: 150,
    integrity: 300,
    type: '1handMelee',
    minDamage: 7,
    maxDamage: 13,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '543',
    name: 'Rouleau à Pâtisserie',
    image:
      '/assets/items/ROULEAU-PATISSERIE_262px.webp',
    tech: 80,
    integrity: 100,
    type: '1handMelee',
    minDamage: 8,
    maxDamage: 36,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 80,
      },
    ],
  },
  {
    id: '544',
    name: 'Poêle',
    image: '/assets/items/POELLE_262px.webp',
    tech: 280,
    integrity: 80,
    type: '1handMelee',
    minDamage: 5,
    maxDamage: 25,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 80,
      },
    ],
  },
  {
    id: '545',
    name: 'Chalumeau',
    image: '/assets/items/Chalumeau.webp',
    tech: 320,
    integrity: 140,
    type: '1handMelee',
    minDamage: 20,
    maxDamage: 32,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'engineering',
        value: 150,
      },
    ],
    effects: [
      {
        property: 'engineering',
        value: 5,
      },
    ],
  },
  {
    id: '546',
    name: 'Clef à molette',
    image: '/assets/items/CLE-Molette_262px.webp',
    tech: 300,
    integrity: 80,
    type: '1handMelee',
    minDamage: 6,
    maxDamage: 30,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'engineering',
        value: 150,
      },
    ],
    effects: [
      {
        property: 'engineering',
        value: 5,
      },
    ],
  },
  {
    id: '547',
    name: 'Tazer',
    image: '/assets/items/Tazer.webp',
    tech: 0,
    integrity: 250,
    type: '1handMelee',
    minDamage: 10,
    maxDamage: 44,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 50,
      },
      {
        property: 'agility',
        value: 50,
      },
    ],
  },
  {
    id: '548',
    name: 'Tronçolame',
    image: '/assets/items/TRONCOLAME.webp',
    tech: 480,
    integrity: 200,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '549',
    name: 'Canne',
    image: '/assets/items/Canne.webp',
    tech: 80,
    integrity: 160,
    type: '1handMelee',
    minDamage: 22,
    maxDamage: 32,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '550',
    name: 'Pelle',
    image: '/assets/items/Pelle.webp',
    tech: 180,
    integrity: 200,
    type: '2handsMelee',
    minDamage: 24,
    maxDamage: 32,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '551',
    name: 'Détecteur',
    image: '/assets/items/Pelle.webp',
    tech: 0,
    integrity: 0,
    type: '2handsMelee',
    minDamage: 0,
    maxDamage: 0,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '552',
    name: 'City Eagle',
    image: '/assets/items/CITY-EAGLE_262px.webp',
    tech: 320,
    integrity: 120,
    type: '1handShot',
    minDamage: 9,
    maxDamage: 31,
    hitsPerRound: 1,
    hands: 1,
    reach: 1,
    prerequisites: [
      {
        property: 'strength',
        value: 60,
      },
      {
        property: 'perception',
        value: 80,
      },
    ],
  },
  {
    id: '553',
    name: 'Double revolver calibre .32',
    image: '/assets/items/Doublecalibre32.webp',
    tech: 240,
    integrity: 110,
    type: '1handShot',
    minDamage: 11,
    maxDamage: 15,
    hitsPerRound: 2,
    hands: 1,
    reach: 2,
    effects: [
      {
        property: 'agility',
        value: 7,
      },
    ],
  },
  {
    id: '554',
    name: 'FI2615',
    image: '/assets/items/FI2615_IMPERIAL2.webp',
    tech: 120,
    integrity: 140,
    type: '2handsShot',
    minDamage: 7,
    maxDamage: 31,
    hitsPerRound: 3,
    hands: 2,
    reach: 6,
    prerequisites: [
      {
        property: 'perception',
        value: 110,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: 5,
      },
    ],
  },
  {
    id: '555',
    name: 'Fusil Lincoln',
    image: '/assets/items/FUSIL_LINCOLN262.webp',
    tech: 450,
    integrity: 200,
    type: '2handsShot',
    minDamage: 22,
    maxDamage: 46,
    hitsPerRound: 1,
    hands: 2,
    reach: 9,
  },
  {
    id: '556',
    name: 'Fusil T31',
    image: '/assets/items/FUSIL_T31_262px.webp',
    tech: 200,
    integrity: 80,
    type: '2handsShot',
    minDamage: 18,
    maxDamage: 36,
    hitsPerRound: 2,
    hands: 2,
    reach: 4,
    prerequisites: [
      {
        property: 'strength',
        value: 110,
      },
      {
        property: 'perception',
        value: 80,
      },
    ],
  },
  {
    id: '557',
    name: 'Gold Eagle',
    image: '/assets/items/Deaglegold.webp',
    tech: 320,
    integrity: 120,
    type: '1handShot',
    minDamage: 23,
    maxDamage: 33,
    hitsPerRound: 1,
    hands: 1,
    reach: 3,
    prerequisites: [
      {
        property: 'strength',
        value: 20,
      },
      {
        property: 'perception',
        value: 20,
      },
    ],
  },
  {
    id: '558',
    name: 'Haka 47',
    image: '/assets/items/Haka47.webp',
    tech: 120,
    integrity: 300,
    type: '2handsShot',
    minDamage: 12,
    maxDamage: 26,
    hitsPerRound: 3,
    hands: 2,
    reach: 5,
    prerequisites: [
      {
        property: 'perception',
        value: 100,
      },
    ],
  },
  {
    id: '559',
    name: 'Magnum à lunette',
    image: '/assets/items/MAGNUM-A-LUNETTE262.webp',
    tech: 550,
    integrity: 130,
    type: '1handShot',
    minDamage: 11,
    maxDamage: 23,
    hitsPerRound: 1,
    hands: 1,
    reach: 3,
    effects: [
      {
        property: 'perception',
        value: 5,
      },
    ],
  },
  {
    id: '560',
    name: 'Minigun',
    image: '/assets/items/Minigun.webp',
    tech: 115,
    integrity: 400,
    type: '2handsShot',
    minDamage: 13,
    maxDamage: 19,
    hitsPerRound: 3,
    hands: 2,
    reach: 5,
    prerequisites: [
      {
        property: 'strength',
        value: 80,
      },
      {
        property: 'perception',
        value: 40,
      },
    ],
  },
  {
    id: '561',
    name: 'Pistolet 9mm',
    image: '/assets/items/NEO-BERETTA_9mm_262px.webp',
    tech: 240,
    integrity: 150,
    type: '1handShot',
    minDamage: 12,
    maxDamage: 30,
    hitsPerRound: 1,
    hands: 1,
    reach: 5,
    prerequisites: [
      {
        property: 'perception',
        value: 60,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: 7,
      },
    ],
  },
  {
    id: '562',
    name: 'Revolver calibre .32',
    image: '/assets/items/Calibre32.webp',
    tech: 240,
    integrity: 110,
    type: '1handShot',
    minDamage: 12,
    maxDamage: 30,
    hitsPerRound: 1,
    hands: 1,
    reach: 1,
    prerequisites: [
      {
        property: 'agility',
        value: 40,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: 7,
      },
    ],
  },
  {
    id: '563',
    name: 'Revolver calibre .40',
    image: '/assets/items/Calibre40.webp',
    tech: 240,
    integrity: 130,
    type: '1handShot',
    minDamage: 11,
    maxDamage: 31,
    hitsPerRound: 1,
    hands: 1,
    reach: 1,
    prerequisites: [
      {
        property: 'agility',
        value: 40,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: 7,
      },
    ],
  },
  {
    id: '564',
    name: 'Sulfateuse',
    image: '/assets/items/SULFATEUSE262.webp',
    tech: 130,
    integrity: 350,
    type: '2handsShot',
    minDamage: 2,
    maxDamage: 14,
    hitsPerRound: 5,
    hands: 2,
    reach: 5,
  },
  {
    id: '565',
    name: 'XVI',
    image: '/assets/items/Xvi.webp',
    tech: 260,
    integrity: 100,
    type: '2handsShot',
    minDamage: 6,
    maxDamage: 20,
    hitsPerRound: 3,
    hands: 2,
    reach: 6,
    prerequisites: [
      {
        property: 'agility',
        value: 60,
      },
      {
        property: 'perception',
        value: 80,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: 10,
      },
    ],
  },
  {
    id: '566',
    name: 'Gun A 317',
    image:
      '/assets/items/A-317_REVOLVER_MAGNUS_BLEU_262-PX.webp',
    tech: 320,
    integrity: 300,
    type: '1handShot',
    minDamage: 6,
    maxDamage: 12,
    hitsPerRound: 2,
    hands: 1,
    reach: 4,
  },
  {
    id: '567',
    name: 'Fusil A 317 T',
    image:
      '/assets/items/A-317_FUSIL_D_ASSAULT_GRIPPIN_ROUGE_262-PX.webp',
    tech: 470,
    integrity: 300,
    type: '2handsShot',
    minDamage: 24,
    maxDamage: 42,
    hitsPerRound: 1,
    hands: 2,
    reach: 12,
  },
  {
    id: '568',
    name: 'Fusil A 332',
    image: '/assets/items/A332WEAPON_PM_ROUGE.webp',
    tech: 130,
    integrity: 350,
    type: '2handsShot',
    minDamage: 2,
    maxDamage: 14,
    hitsPerRound: 5,
    hands: 2,
    reach: 5,
  },
  {
    id: '569',
    name: 'Azmat',
    image: '/assets/items/AZMAT262.webp',
    tech: 320,
    integrity: 90,
    type: '1handShot',
    minDamage: 6,
    maxDamage: 12,
    hitsPerRound: 2,
    hands: 1,
    reach: 4,
  },
  {
    id: '570',
    name: 'Flingue plasma',
    image: '/assets/items/FLINGUE_PLASMA262.webp',
    tech: 550,
    integrity: 130,
    type: '1handShot',
    minDamage: 11,
    maxDamage: 21,
    hitsPerRound: 1,
    hands: 1,
    reach: 3,
  },
  {
    id: '571',
    name: 'Fusil laser',
    image: '/assets/items/FUSIL_LASER2.webp',
    tech: 470,
    integrity: 145,
    type: '2handsShot',
    minDamage: 24,
    maxDamage: 42,
    hitsPerRound: 1,
    hands: 2,
    reach: 12,
    prerequisites: [
      {
        property: 'perception',
        value: 150,
      },
    ],
  },
  {
    id: '572',
    name: 'Fusil plasma',
    image: '/assets/items/Plasma.webp',
    tech: 0,
    integrity: 85,
    type: '2handsShot',
    minDamage: 24,
    maxDamage: 40,
    hitsPerRound: 1,
    hands: 2,
    reach: 2,
    prerequisites: [
      {
        property: 'strength',
        value: 50,
      },
      {
        property: 'perception',
        value: 50,
      },
    ],
  },
  {
    id: '573',
    name: 'Gatling laser',
    image: '/assets/items/Gatling_Laser2.webp',
    tech: 260,
    integrity: 100,
    type: '2handsShot',
    minDamage: 12,
    maxDamage: 22,
    hitsPerRound: 3,
    hands: 2,
    reach: 3,
    prerequisites: [
      {
        property: 'strength',
        value: 120,
      },
      {
        property: 'perception',
        value: 60,
      },
      {
        property: 'robustness',
        value: 100,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -10,
      },
      {
        property: 'perception',
        value: -35,
      },
    ],
  },
  {
    id: '574',
    name: 'Pulseur',
    image: '/assets/items/Pulseur.webp',
    tech: 340,
    integrity: 115,
    type: '1handShot',
    minDamage: 16,
    maxDamage: 26,
    hitsPerRound: 1,
    hands: 1,
    reach: 4,
    prerequisites: [
      {
        property: 'agility',
        value: 60,
      },
      {
        property: 'perception',
        value: 60,
      },
    ],
  },
  {
    id: '575',
    name: 'V42J4',
    image: '/assets/items/V42J4_262px.webp',
    tech: 260,
    integrity: 120,
    type: '2handsShot',
    minDamage: 20,
    maxDamage: 26,
    hitsPerRound: 2,
    hands: 2,
    reach: 7,
    prerequisites: [
      {
        property: 'agility',
        value: 80,
      },
      {
        property: 'perception',
        value: 80,
      },
    ],
  },
  {
    id: '576',
    name: 'Runner',
    image: '/assets/items/Runner_262.webp',
    tech: 320,
    integrity: 90,
    type: '1handShot',
    minDamage: 3,
    maxDamage: 15,
    hitsPerRound: 2,
    hands: 1,
    reach: 4,
    prerequisites: [
      {
        property: 'perception',
        value: 150,
      },
    ],
  },
  {
    id: '577',
    name: 'Canon Anti-matériel',
    image: '/assets/items/Gatling_G1.webp',
    tech: 260,
    integrity: 100,
    type: '2handsShot',
    minDamage: 18,
    maxDamage: 42,
    hitsPerRound: 2,
    hands: 2,
    reach: 5,
    prerequisites: [
      {
        property: 'strength',
        value: 120,
      },
      {
        property: 'perception',
        value: 60,
      },
      {
        property: 'robustness',
        value: 100,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -10,
      },
      {
        property: 'perception',
        value: -35,
      },
    ],
  },
  {
    id: '578',
    name: 'Fusil Sniper Laser',
    image: '/assets/items/Fusilsniper.webp',
    tech: 470,
    integrity: 145,
    type: '2handsShot',
    minDamage: 36,
    maxDamage: 48,
    hitsPerRound: 1,
    hands: 2,
    reach: 14,
    prerequisites: [
      {
        property: 'perception',
        value: 150,
      },
    ],
  },
  {
    id: '579',
    name: 'F.I.S.T',
    image: '/assets/items/Fusil_iem.webp',
    tech: 500,
    integrity: 130,
    type: '1handShot',
    minDamage: 13,
    maxDamage: 25,
    hitsPerRound: 1,
    hands: 1,
    reach: 6,
    effects: [
      {
        property: 'perception',
        value: 5,
      },
    ],
  },
  {
    id: '580',
    name: 'Lance-flammes',
    image: '/assets/items/LANCE-FLAME2.webp',
    tech: 0,
    integrity: 110,
    type: '2handsShot',
    minDamage: 12,
    maxDamage: 60,
    hitsPerRound: 2,
    hands: 2,
    reach: 4,
    prerequisites: [
      {
        property: 'strength',
        value: 80,
      },
      {
        property: 'robustness',
        value: 80,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -5,
      },
    ],
  },
  {
    id: '581',
    name: 'Arbalète automatique',
    image: '/assets/items/Arba-auto.webp',
    tech: 320,
    integrity: 250,
    type: '1handShot',
    minDamage: 15,
    maxDamage: 25,
    hitsPerRound: 1,
    hands: 1,
    reach: 4,
    prerequisites: [
      {
        property: 'agility',
        value: 70,
      },
      {
        property: 'perception',
        value: 70,
      },
    ],
  },
  {
    id: '582',
    name: 'Arc à positron',
    image: '/assets/items/Arc_positrons.webp',
    tech: 450,
    integrity: 150,
    type: '2handsShot',
    minDamage: 20,
    maxDamage: 48,
    hitsPerRound: 1,
    hands: 2,
    reach: 9,
    prerequisites: [
      {
        property: 'agility',
        value: 180,
      },
      {
        property: 'perception',
        value: 100,
      },
    ],
    effects: [
      {
        property: 'perception',
        value: 5,
      },
    ],
  },
  {
    id: '583',
    name: 'Arc de contrôle',
    image: '/assets/items/Arc_controle_bleu.webp',
    tech: 460,
    integrity: 150,
    type: '2handsShot',
    minDamage: 22,
    maxDamage: 40,
    hitsPerRound: 1,
    hands: 2,
    reach: 12,
    prerequisites: [
      {
        property: 'agility',
        value: 120,
      },
      {
        property: 'perception',
        value: 150,
      },
    ],
  },
  {
    id: '584',
    name: 'Arc à poulie',
    image: '/assets/items/Arc_a_poulie.webp',
    tech: 450,
    integrity: 180,
    type: '2handsShot',
    minDamage: 18,
    maxDamage: 48,
    hitsPerRound: 1,
    hands: 2,
    reach: 9,
    prerequisites: [
      {
        property: 'agility',
        value: 120,
      },
      {
        property: 'perception',
        value: 120,
      },
    ],
  },
  {
    id: '585',
    name: 'Pistaclou',
    image: '/assets/items/PISTACLOUS262.webp',
    tech: 80,
    integrity: 80,
    type: '1handShot',
    minDamage: 7,
    maxDamage: 13,
    hitsPerRound: 3,
    hands: 1,
    reach: 1,
  },
  {
    id: '586',
    name: 'Pistoconfetti',
    image: '/assets/items/Pistoconfetti.webp',
    tech: 0,
    integrity: 1,
    type: '1handShot',
    minDamage: 0,
    maxDamage: 2,
    hitsPerRound: 1,
    hands: 1,
    reach: 1,
  },
  {
    id: '587',
    name: 'Pistolet à billes',
    image: '/assets/items/Pisto-bille.webp',
    tech: 50,
    integrity: 200,
    type: '1handShot',
    minDamage: 2,
    maxDamage: 4,
    hitsPerRound: 1,
    hands: 1,
    reach: 1,
  },
  {
    id: '588',
    name: 'Pistolet à ventouses',
    image: '/assets/items/Pisto-ventouse.webp',
    tech: 0,
    integrity: 120,
    type: '1handShot',
    minDamage: 0,
    maxDamage: 2,
    hitsPerRound: 1,
    hands: 1,
    reach: 1,
  },
  {
    id: '589',
    name: 'Railgun',
    image: '/assets/items/RAIL-GUN262.webp',
    tech: 260,
    integrity: 60,
    type: '2handsShot',
    minDamage: 10,
    maxDamage: 70,
    hitsPerRound: 1,
    hands: 2,
    reach: 10,
  },
  {
    id: '590',
    name: 'Vibrolame',
    image: '/assets/items/Vibrolame.webp',
    tech: 360,
    integrity: 150,
    type: '1handShot',
    minDamage: 20,
    maxDamage: 36,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 110,
      },
    ],
  },
  {
    id: '591',
    name: 'Dardepoing',
    image: '/assets/items/Dardepoing.webp',
    tech: 120,
    integrity: 200,
    type: '1handMelee',
    effects: [
      {
        property: 'strength',
        value: 5,
      },
    ],
    minDamage: 20,
    maxDamage: 38,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '592',
    name: 'Gants Dreadball',
    image: '/assets/items/Gants_dreadball.webp',
    tech: 240,
    integrity: 300,
    type: '2handsMelee',
    prerequisites: [
      {
        property: 'strength',
        value: 50,
      },
    ],
    effects: [
      {
        property: 'strength',
        value: 5,
      },
    ],
    minDamage: 38,
    maxDamage: 70,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '593',
    name: 'Gants de fer',
    image: '/assets/items/Gant-de-fer.webp',
    tech: 240,
    integrity: 300,
    type: '2handsMelee',
    prerequisites: [
      {
        property: 'strength',
        value: 50,
      },
    ],
    effects: [
      {
        property: 'strength',
        value: 5,
      },
    ],
    minDamage: 38,
    maxDamage: 70,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '594',
    name: 'Golden Punch',
    image: '/assets/items/Golden_punch.webp',
    tech: 0,
    integrity: 300,
    type: '2handsMelee',
    effects: [
      {
        property: 'agility',
        value: 20,
      },
    ],
    minDamage: 3,
    maxDamage: 7,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '595',
    name: 'Gants techno sombres',
    image: '/assets/items/Gants_techno_sombres.webp',
    tech: 60,
    integrity: 100,
    type: '2handsMelee',
    prerequisites: [
      {
        property: 'computing',
        value: 150,
      },
      {
        property: 'agility',
        value: 130,
      },
    ],
    effects: [
      {
        property: 'computing',
        value: 10,
      },
    ],
    minDamage: 2,
    maxDamage: 6,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '596',
    name: 'Bracelet A323',
    image: '/assets/items/Braclet_A323.webp',
    tech: 360,
    integrity: 300,
    type: '1handMelee',
    minDamage: 21,
    maxDamage: 31,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '597',
    name: 'Épée A317N',
    image: '/assets/items/A-317_SABRE_BLEU_262-PX.webp',
    tech: 460,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '598',
    name: 'Épée A317P',
    image: '/assets/items/A-317_SABRE_BLEU_262-PX.webp',
    tech: 60,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'robustness',
        value: 40,
      },
      {
        property: 'speed',
        value: -2,
      },
    ],
  },
  {
    id: '599',
    name: 'Ironix',
    image: '/assets/items/Ironix.webp',
    tech: 180,
    integrity: 120,
    type: '2handsMelee',
    minDamage: 50,
    maxDamage: 78,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 120,
      },
      {
        property: 'agility',
        value: 110,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -5,
      },
    ],
  },
  {
    id: '600',
    name: 'Technohache',
    image: '/assets/items/Hache_techno.webp',
    tech: 240,
    integrity: 160,
    type: '1handMelee',
    minDamage: 22,
    maxDamage: 34,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 60,
      },
      {
        property: 'agility',
        value: 120,
      },
    ],
  },
  {
    id: '601',
    name: 'Chaine cloutée',
    image: '/assets/items/Chaine_cloutee.webp',
    tech: 320,
    integrity: 140,
    type: '1handMelee',
    minDamage: 20,
    maxDamage: 32,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 130,
      },
    ],
  },
  {
    id: '602',
    name: 'Gun A370',
    image: '/assets/items/Gun_A370.webp',
    tech: 320,
    integrity: 300,
    type: '1handShot',
    minDamage: 6,
    maxDamage: 12,
    hitsPerRound: 2,
    hands: 1,
    reach: 4,
  },
  {
    id: '603',
    name: 'Arc électrique',
    image: '/assets/items/Arc_electrique.webp',
    tech: 450,
    integrity: 150,
    type: '2handsShot',
    minDamage: 20,
    maxDamage: 48,
    hitsPerRound: 1,
    hands: 2,
    reach: 9,
    prerequisites: [
      {
        property: 'agility',
        value: 180,
      },
      {
        property: 'perception',
        value: 100,
      },
    ],
    effects: [
      {
        property: 'perception',
        value: 5,
      },
    ],
  },
  {
    id: '604',
    name: 'RedBow',
    image: '/assets/items/Redbow.webp',
    tech: 460,
    integrity: 150,
    type: '2handsShot',
    minDamage: 22,
    maxDamage: 40,
    hitsPerRound: 1,
    hands: 2,
    reach: 12,
    prerequisites: [
      {
        property: 'agility',
        value: 120,
      },
      {
        property: 'perception',
        value: 150,
      },
    ],
  },
];
