import type { ItemResponseDto } from './item.dto';

export const MOCK_WEAPONS_ITEMS: ItemResponseDto[] = [
  {
    id: '500',
    name: 'Bistouri',
    image: 'https://wiki.dreadcast.net/images/b/bf/Bistouri70.png',
    tech: 60,
    integrity: 100,
    type: '2handsMelee',
    prerequisites: [
      {
        property: 'medicine',
        value: 150,
      },
    ],
    effects: [
      {
        property: 'medicine',
        value: 10,
      },
    ],
    minDamage: 4,
    maxDamage: 12,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '501',
    name: 'Dague énergétique',
    image:
      'https://wiki.dreadcast.net/images/thumb/f/f2/DAGUE_ENERGETIQUE262.png/150px-DAGUE_ENERGETIQUE262.png',
    tech: 350,
    integrity: 150,
    type: '1handMelee',
    effects: [
      {
        property: 'agility',
        value: 10,
      },
    ],
    minDamage: 20,
    maxDamage: 30,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '502',
    name: 'Kanuf',
    image:
      'https://wiki.dreadcast.net/images/thumb/6/6b/KANUF_262px.png/100px-KANUF_262px.png',
    tech: 300,
    integrity: 50,
    type: '1handMelee',
    effects: [
      {
        property: 'agility',
        value: 5,
      },
    ],
    minDamage: 24,
    maxDamage: 32,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '503',
    name: 'Poing américain/Dardepoing',
    image: 'https://wiki.dreadcast.net/images/e/e8/Poing_americain.png',
    tech: 120,
    integrity: 200,
    type: '1handMelee',
    effects: [
      {
        property: 'strength',
        value: 5,
      },
    ],
    minDamage: 20,
    maxDamage: 38,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '504',
    name: 'Gants Cyber/Gants Dreadball/Gants de fer',
    image: 'https://wiki.dreadcast.net/images/6/65/Gants_bijou.png',
    tech: 240,
    integrity: 300,
    type: '2handsMelee',
    prerequisites: [
      {
        property: 'strength',
        value: 50,
      },
    ],
    effects: [
      {
        property: 'strength',
        value: 5,
      },
    ],
    minDamage: 38,
    maxDamage: 70,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '505',
    name: 'Gants de boxe/Golden Punch',
    image: 'https://wiki.dreadcast.net/images/9/9f/Gant_boxe.png',
    tech: 0,
    integrity: 300,
    type: '2handsMelee',
    effects: [
      {
        property: 'agility',
        value: 20,
      },
    ],
    minDamage: 3,
    maxDamage: 7,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '506',
    name: 'Gant Hydro',
    image:
      'https://wiki.dreadcast.net/images/thumb/0/0e/GANTS_HYDRO262.png/100px-GANTS_HYDRO262.png',
    tech: 240,
    integrity: 120,
    type: '1handMelee',
    effects: [
      {
        property: 'strength',
        value: 8,
      },
    ],
    minDamage: 16,
    maxDamage: 36,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '507',
    name: 'Gants à piques',
    image: 'https://wiki.dreadcast.net/images/f/f4/Gant-a-pik.png',
    tech: 300,
    integrity: 250,
    type: '2handsMelee',
    prerequisites: [
      {
        property: 'strength',
        value: 50,
      },
    ],
    effects: [
      {
        property: 'strength',
        value: 5,
      },
    ],
    minDamage: 38,
    maxDamage: 64,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '508',
    name: 'Gants en cuir',
    image: 'https://wiki.dreadcast.net/images/a/a2/Cuirgants.png',
    tech: 360,
    integrity: 80,
    type: '2handsMelee',
    effects: [
      {
        property: 'stealth',
        value: 15,
      },
    ],
    minDamage: 2,
    maxDamage: 6,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '509',
    name: 'Gants technologiques/Gants techno sombres',
    image: 'https://wiki.dreadcast.net/images/0/0d/Gant-info999.png',
    tech: 60,
    integrity: 100,
    type: '2handsMelee',
    prerequisites: [
      {
        property: 'computing',
        value: 150,
      },
      {
        property: 'agility',
        value: 130,
      },
    ],
    effects: [
      {
        property: 'computing',
        value: 10,
      },
    ],
    minDamage: 2,
    maxDamage: 6,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '510',
    name: 'Wolfers',
    image:
      'https://wiki.dreadcast.net/images/thumb/4/47/WOLFERS262.png/150px-WOLFERS262.png',
    tech: 300,
    integrity: 160,
    type: '2handsMelee',
    effects: [
      {
        property: 'agility',
        value: 10,
      },
    ],
    minDamage: 22,
    maxDamage: 78,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '511',
    name: 'Exo gants',
    image:
      'https://wiki.dreadcast.net/images/thumb/5/56/Exosquelette-main.png/100px-Exosquelette-main.png',
    tech: 80,
    integrity: 150,
    type: '2handsMelee',
    prerequisites: [
      {
        property: 'engineering',
        value: 150,
      },
    ],
    effects: [
      {
        property: 'engineering',
        value: 10,
      },
    ],
    minDamage: 38,
    maxDamage: 68,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '512',
    name: 'Gantelet du Juge',
    image:
      'https://wiki.dreadcast.net/images/thumb/f/f1/Gantlet_bleu.png/100px-Gantlet_bleu.png',
    tech: 320,
    integrity: 240,
    type: '2handsMelee',
    effects: [
      {
        property: 'strength',
        value: 15,
      },
    ],
    minDamage: 18,
    maxDamage: 38,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '513',
    name: 'Gantelet Steak',
    image:
      'https://wiki.dreadcast.net/images/thumb/7/79/Gants_steak.png/100px-Gants_steak.png',
    tech: 60,
    integrity: 60,
    type: '2handsMelee',
    prerequisites: [
      {
        property: 'agility',
        value: 75,
      },
      {
        property: 'stealth',
        value: 75,
      },
    ],
    effects: [
      {
        property: 'stealth',
        value: 17,
      },
    ],
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '514',
    name: 'Gantelet A323/Bracelet A323',
    image: 'https://wiki.dreadcast.net/images/7/78/Gant_A323.png',
    tech: 360,
    integrity: 300,
    type: '1handMelee',
    minDamage: 21,
    maxDamage: 31,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '515',
    name: 'Gantelet AXXXN/Épée A317N',
    image:
      'https://wiki.dreadcast.net/images/thumb/a/a2/Gants_A-S9.png/100px-Gants_A-S9.png',
    tech: 460,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '516',
    name: 'Gantelet AXXXP/Épée A317P',
    image:
      'https://wiki.dreadcast.net/images/thumb/a/a2/Gants_A-S9.png/100px-Gants_A-S9.png',
    tech: 60,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'robustness',
        value: 40,
      },
      {
        property: 'speed',
        value: -2,
      },
    ],
  },
  {
    id: '517',
    name: 'Gantelet AXXXT',
    image:
      'https://wiki.dreadcast.net/images/thumb/a/a2/Gants_A-S9.png/100px-Gants_A-S9.png',
    tech: 60,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'perception',
        value: 40,
      },
    ],
  },
  {
    id: '518',
    name: 'Gantelet AXXXL',
    image:
      'https://wiki.dreadcast.net/images/thumb/a/a2/Gants_A-S9.png/100px-Gants_A-S9.png',
    tech: 60,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'stealth',
        value: 17,
      },
    ],
  },
  {
    id: '519',
    name: 'Gantelet AXXXJ',
    image:
      'https://wiki.dreadcast.net/images/thumb/a/a2/Gants_A-S9.png/100px-Gants_A-S9.png',
    tech: 60,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'engineering',
        value: 10,
      },
    ],
  },
  {
    id: '520',
    name: 'Gantelet AXXXO',
    image:
      'https://wiki.dreadcast.net/images/thumb/a/a2/Gants_A-S9.png/100px-Gants_A-S9.png',
    tech: 60,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'medicine',
        value: 10,
      },
    ],
  },
  {
    id: '521',
    name: 'Gantelet AXXXD',
    image:
      'https://wiki.dreadcast.net/images/thumb/a/a2/Gants_A-S9.png/100px-Gants_A-S9.png',
    tech: 60,
    integrity: 300,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'computing',
        value: 10,
      },
    ],
  },
  {
    id: '522',
    name: 'Agrimensor',
    image:
      'https://wiki.dreadcast.net/images/thumb/9/9a/AGRI2.png/150px-AGRI2.png',
    tech: 0,
    integrity: 120,
    type: '2handsMelee',
    minDamage: 50,
    maxDamage: 90,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 160,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -10,
      },
    ],
  },
  {
    id: '523',
    name: 'Epée à deux mains',
    image: 'https://wiki.dreadcast.net/images/9/9f/Epee_2m.png',
    tech: 0,
    integrity: 120,
    type: '2handsMelee',
    minDamage: 55,
    maxDamage: 87,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 160,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -10,
      },
    ],
  },
  {
    id: '524',
    name: 'Epée énergétique',
    image: 'https://wiki.dreadcast.net/images/7/7f/Powersword.png',
    tech: 100,
    integrity: 180,
    type: '2handsMelee',
    minDamage: 40,
    maxDamage: 78,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 80,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: 5,
      },
    ],
  },
  {
    id: '525',
    name: 'Epée quantique',
    image: 'https://wiki.dreadcast.net/images/a/ad/Epee_quantique.png',
    tech: 320,
    integrity: 200,
    type: '2handsMelee',
    minDamage: 40,
    maxDamage: 78,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 80,
      },
    ],
    effects: [
      {
        property: 'strength',
        value: -10,
      },
    ],
  },
  {
    id: '526',
    name: 'Katana',
    image:
      'https://wiki.dreadcast.net/images/thumb/0/08/KATANNA_262px.png/150px-KATANNA_262px.png',
    tech: 320,
    integrity: 140,
    type: '1handMelee',
    minDamage: 14,
    maxDamage: 36,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 120,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: 5,
      },
    ],
  },
  {
    id: '527',
    name: 'Tranchoir à fusion',
    image: 'https://wiki.dreadcast.net/images/a/af/Tranchoir_fusion.png',
    tech: 200,
    integrity: 130,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 90,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 150,
      },
      {
        property: 'engineering',
        value: 110,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -5,
      },
    ],
  },
  {
    id: '528',
    name: 'Lame carbone A370',
    image:
      'https://wiki.dreadcast.net/images/thumb/b/b9/Lame-A370.png/150px-Lame-A370.png',
    tech: 0,
    integrity: 200,
    type: '2handsMelee',
    minDamage: 50,
    maxDamage: 90,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'agility',
        value: -10,
      },
    ],
  },
  {
    id: '529',
    name: 'Blizzaxe/Ironix',
    image: 'https://wiki.dreadcast.net/images/d/d4/Hacheglace.png',
    tech: 180,
    integrity: 120,
    type: '2handsMelee',
    minDamage: 50,
    maxDamage: 78,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 120,
      },
      {
        property: 'agility',
        value: 110,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -5,
      },
    ],
  },
  {
    id: '530',
    name: 'Hache rustique/Technohache',
    image: 'https://wiki.dreadcast.net/images/3/37/Hache_rustique.png',
    tech: 240,
    integrity: 160,
    type: '1handMelee',
    minDamage: 22,
    maxDamage: 34,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 60,
      },
      {
        property: 'agility',
        value: 120,
      },
    ],
  },
  {
    id: '531',
    name: 'Koup Koup',
    image: 'https://wiki.dreadcast.net/images/7/7a/Koup_koup.png',
    tech: 180,
    integrity: 160,
    type: '2handsMelee',
    minDamage: 44,
    maxDamage: 84,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 160,
      },
      {
        property: 'agility',
        value: 110,
      },
    ],
  },
  {
    id: '532',
    name: 'Bouclier',
    image: 'https://wiki.dreadcast.net/images/8/87/Bouclier.png',
    tech: 0,
    integrity: 250,
    type: '1handMelee',
    minDamage: 13,
    maxDamage: 23,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 150,
      },
    ],
    effects: [
      {
        property: 'robustness',
        value: 20,
      },
      {
        property: 'speed',
        value: -1,
      },
    ],
  },
  {
    id: '533',
    name: 'Bouclier énergétique',
    image: 'https://wiki.dreadcast.net/images/5/5d/Powerbouclier.png',
    tech: 0,
    integrity: 120,
    type: '1handMelee',
    minDamage: 20,
    maxDamage: 30,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    effects: [
      {
        property: 'robustness',
        value: 10,
      },
    ],
  },
  {
    id: '534',
    name: 'Batte de dreadball',
    image:
      'https://wiki.dreadcast.net/images/thumb/7/71/BATTE-DE-BASEBALL262.png/100px-BATTE-DE-BASEBALL262.png',
    tech: 80,
    integrity: 450,
    type: '1handMelee',
    minDamage: 24,
    maxDamage: 34,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '535',
    name: 'Batte de dreadball cloutée',
    image: 'https://wiki.dreadcast.net/images/2/29/Batte-a-clou.png',
    tech: 120,
    integrity: 400,
    type: '1handMelee',
    minDamage: 10,
    maxDamage: 26,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '536',
    name: 'Fouet/Chaine cloutée',
    image: 'https://wiki.dreadcast.net/images/5/5a/Fouet.png',
    tech: 320,
    integrity: 140,
    type: '1handMelee',
    minDamage: 20,
    maxDamage: 32,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 130,
      },
    ],
  },
  {
    id: '537',
    name: 'Hallebarde',
    image: 'https://wiki.dreadcast.net/images/b/b1/Hallebarde.png',
    tech: 0,
    integrity: 200,
    type: '2handsMelee',
    minDamage: 48,
    maxDamage: 86,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 120,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -7,
      },
    ],
  },
  {
    id: '538',
    name: 'Masse énergétique',
    image: 'https://wiki.dreadcast.net/images/4/48/Masse_energetique.png',
    tech: 320,
    integrity: 320,
    type: '2handsMelee',
    minDamage: 52,
    maxDamage: 84,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
    effects: [
      {
        property: 'agility',
        value: -20,
      },
    ],
  },
  {
    id: '539',
    name: 'Monofilament',
    image:
      'https://wiki.dreadcast.net/images/thumb/2/28/MONOFILAMENT262.png/100px-MONOFILAMENT262.png',
    tech: 240,
    integrity: 240,
    type: '2handsMelee',
    minDamage: 1,
    maxDamage: 99,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '540',
    name: 'Petite cuillère de la destruction',
    image: 'https://wiki.dreadcast.net/images/a/a2/Petite_cuillere.png',
    tech: 0,
    integrity: 9999,
    type: '2handsMelee',
    minDamage: 99,
    maxDamage: 999,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '541',
    name: 'Pied de biche',
    image: 'https://wiki.dreadcast.net/images/0/0d/Pied_biche.png',
    tech: 0,
    integrity: 250,
    type: '1handMelee',
    minDamage: 14,
    maxDamage: 48,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 50,
      },
      {
        property: 'agility',
        value: 50,
      },
    ],
  },
  {
    id: '542',
    name: 'Rouleau en poly tétra fluoro éthylène',
    image:
      'https://wiki.dreadcast.net/images/thumb/a/a2/ROULEAU-PATISSERIE_262px.png/150px-ROULEAU-PATISSERIE_262px.png',
    tech: 150,
    integrity: 300,
    type: '1handMelee',
    minDamage: 7,
    maxDamage: 13,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '543',
    name: 'Rouleau à Pâtisserie',
    image:
      'https://wiki.dreadcast.net/images/thumb/a/a2/ROULEAU-PATISSERIE_262px.png/150px-ROULEAU-PATISSERIE_262px.png',
    tech: 80,
    integrity: 100,
    type: '1handMelee',
    minDamage: 8,
    maxDamage: 36,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 80,
      },
    ],
  },
  {
    id: '544',
    name: 'Poêle',
    image:
      'https://wiki.dreadcast.net/images/thumb/b/b0/POELLE_262px.png/150px-POELLE_262px.png',
    tech: 280,
    integrity: 80,
    type: '1handMelee',
    minDamage: 5,
    maxDamage: 25,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 80,
      },
    ],
  },
  {
    id: '545',
    name: 'Chalumeau',
    image:
      'https://wiki.dreadcast.net/images/thumb/c/cb/Chalumeau.png/150px-Chalumeau.png',
    tech: 320,
    integrity: 140,
    type: '1handMelee',
    minDamage: 20,
    maxDamage: 32,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'engineering',
        value: 150,
      },
    ],
    effects: [
      {
        property: 'engineering',
        value: 5,
      },
    ],
  },
  {
    id: '546',
    name: 'Clef à molette',
    image:
      'https://wiki.dreadcast.net/images/thumb/b/b8/CLE-Molette_262px.png/100px-CLE-Molette_262px.png',
    tech: 300,
    integrity: 80,
    type: '1handMelee',
    minDamage: 6,
    maxDamage: 30,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'engineering',
        value: 150,
      },
    ],
    effects: [
      {
        property: 'engineering',
        value: 5,
      },
    ],
  },
  {
    id: '547',
    name: 'Tazer',
    image: 'https://wiki.dreadcast.net/images/a/ac/Tazer.png',
    tech: 0,
    integrity: 250,
    type: '1handMelee',
    minDamage: 10,
    maxDamage: 44,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'strength',
        value: 50,
      },
      {
        property: 'agility',
        value: 50,
      },
    ],
  },
  {
    id: '548',
    name: 'Tronçolame',
    image:
      'https://wiki.dreadcast.net/images/thumb/a/ab/TRONCOLAME.png/150px-TRONCOLAME.png',
    tech: 480,
    integrity: 200,
    type: '2handsMelee',
    minDamage: 34,
    maxDamage: 66,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '549',
    name: 'Canne',
    image:
      'https://wiki.dreadcast.net/images/thumb/f/fe/Canne.png/100px-Canne.png',
    tech: 80,
    integrity: 160,
    type: '1handMelee',
    minDamage: 22,
    maxDamage: 32,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
  },
  {
    id: '550',
    name: 'Pelle',
    image: 'https://wiki.dreadcast.net/images/f/f9/Pelle.png',
    tech: 180,
    integrity: 200,
    type: '2handsMelee',
    minDamage: 24,
    maxDamage: 32,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '551',
    name: 'Détecteur',
    image: 'https://wiki.dreadcast.net/images/f/f9/Pelle.png',
    tech: 0,
    integrity: 0,
    type: '2handsMelee',
    minDamage: 0,
    maxDamage: 0,
    hitsPerRound: 1,
    hands: 2,
    reach: 0,
  },
  {
    id: '552',
    name: 'City Eagle',
    image:
      'https://wiki.dreadcast.net/images/thumb/e/e6/CITY-EAGLE_262px.png/150px-CITY-EAGLE_262px.png',
    tech: 320,
    integrity: 120,
    type: '1handShot',
    minDamage: 9,
    maxDamage: 31,
    hitsPerRound: 1,
    hands: 1,
    reach: 1,
    prerequisites: [
      {
        property: 'strength',
        value: 60,
      },
      {
        property: 'perception',
        value: 80,
      },
    ],
  },
  {
    id: '553',
    name: 'Double revolver calibre .32',
    image: 'https://wiki.dreadcast.net/images/d/d2/Doublecalibre32.png',
    tech: 240,
    integrity: 110,
    type: '1handShot',
    minDamage: 11,
    maxDamage: 15,
    hitsPerRound: 2,
    hands: 1,
    reach: 2,
    effects: [
      {
        property: 'agility',
        value: 7,
      },
    ],
  },
  {
    id: '554',
    name: 'FI2615',
    image:
      'https://wiki.dreadcast.net/images/thumb/e/ea/FI2615_IMPERIAL2.png/150px-FI2615_IMPERIAL2.png',
    tech: 120,
    integrity: 140,
    type: '2handsShot',
    minDamage: 7,
    maxDamage: 31,
    hitsPerRound: 3,
    hands: 2,
    reach: 6,
    prerequisites: [
      {
        property: 'perception',
        value: 110,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: 5,
      },
    ],
  },
  {
    id: '555',
    name: 'Fusil Lincoln',
    image:
      'https://wiki.dreadcast.net/images/thumb/6/63/FUSIL_LINCOLN262.png/150px-FUSIL_LINCOLN262.png',
    tech: 450,
    integrity: 200,
    type: '2handsShot',
    minDamage: 22,
    maxDamage: 46,
    hitsPerRound: 1,
    hands: 2,
    reach: 9,
  },
  {
    id: '556',
    name: 'Fusil T31',
    image:
      'https://wiki.dreadcast.net/images/thumb/7/71/FUSIL_T31_262px.png/150px-FUSIL_T31_262px.png',
    tech: 200,
    integrity: 80,
    type: '2handsShot',
    minDamage: 18,
    maxDamage: 36,
    hitsPerRound: 2,
    hands: 2,
    reach: 4,
    prerequisites: [
      {
        property: 'strength',
        value: 110,
      },
      {
        property: 'perception',
        value: 80,
      },
    ],
  },
  {
    id: '557',
    name: 'Gold Eagle',
    image: 'https://wiki.dreadcast.net/images/e/e4/Deaglegold.png',
    tech: 320,
    integrity: 120,
    type: '1handShot',
    minDamage: 23,
    maxDamage: 33,
    hitsPerRound: 1,
    hands: 1,
    reach: 3,
    prerequisites: [
      {
        property: 'strength',
        value: 20,
      },
      {
        property: 'perception',
        value: 20,
      },
    ],
  },
  {
    id: '558',
    name: 'Haka 47',
    image: 'https://wiki.dreadcast.net/images/e/e0/Haka47.png',
    tech: 120,
    integrity: 300,
    type: '2handsShot',
    minDamage: 12,
    maxDamage: 26,
    hitsPerRound: 3,
    hands: 2,
    reach: 5,
    prerequisites: [
      {
        property: 'perception',
        value: 100,
      },
    ],
  },
  {
    id: '559',
    name: 'Magnum à lunette',
    image:
      'https://wiki.dreadcast.net/images/thumb/0/04/MAGNUM-A-LUNETTE262.png/150px-MAGNUM-A-LUNETTE262.png',
    tech: 550,
    integrity: 130,
    type: '1handShot',
    minDamage: 11,
    maxDamage: 23,
    hitsPerRound: 1,
    hands: 1,
    reach: 3,
    effects: [
      {
        property: 'perception',
        value: 5,
      },
    ],
  },
  {
    id: '560',
    name: 'Minigun',
    image: 'https://wiki.dreadcast.net/images/e/eb/Minigun.png',
    tech: 115,
    integrity: 400,
    type: '2handsShot',
    minDamage: 13,
    maxDamage: 19,
    hitsPerRound: 3,
    hands: 2,
    reach: 5,
    prerequisites: [
      {
        property: 'strength',
        value: 80,
      },
      {
        property: 'perception',
        value: 40,
      },
    ],
  },
  {
    id: '561',
    name: 'Pistolet 9mm',
    image:
      'https://wiki.dreadcast.net/images/thumb/a/a3/NEO-BERETTA_9mm_262px.png/150px-NEO-BERETTA_9mm_262px.png',
    tech: 240,
    integrity: 150,
    type: '1handShot',
    minDamage: 12,
    maxDamage: 30,
    hitsPerRound: 1,
    hands: 1,
    reach: 5,
    prerequisites: [
      {
        property: 'perception',
        value: 60,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: 7,
      },
    ],
  },
  {
    id: '562',
    name: 'Revolver calibre .32',
    image: 'https://wiki.dreadcast.net/images/6/6b/Calibre32.png',
    tech: 240,
    integrity: 110,
    type: '1handShot',
    minDamage: 12,
    maxDamage: 30,
    hitsPerRound: 1,
    hands: 1,
    reach: 1,
    prerequisites: [
      {
        property: 'agility',
        value: 40,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: 7,
      },
    ],
  },
  {
    id: '563',
    name: 'Revolver calibre .40',
    image: 'https://wiki.dreadcast.net/images/5/51/Calibre40.png',
    tech: 240,
    integrity: 130,
    type: '1handShot',
    minDamage: 11,
    maxDamage: 31,
    hitsPerRound: 1,
    hands: 1,
    reach: 1,
    prerequisites: [
      {
        property: 'agility',
        value: 40,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: 7,
      },
    ],
  },
  {
    id: '564',
    name: 'Sulfateuse',
    image:
      'https://wiki.dreadcast.net/images/thumb/2/2a/SULFATEUSE262.png/150px-SULFATEUSE262.png',
    tech: 130,
    integrity: 350,
    type: '2handsShot',
    minDamage: 2,
    maxDamage: 14,
    hitsPerRound: 5,
    hands: 2,
    reach: 5,
  },
  {
    id: '565',
    name: 'XVI',
    image: 'https://wiki.dreadcast.net/images/a/a0/Xvi.png',
    tech: 260,
    integrity: 100,
    type: '2handsShot',
    minDamage: 6,
    maxDamage: 20,
    hitsPerRound: 3,
    hands: 2,
    reach: 6,
    prerequisites: [
      {
        property: 'agility',
        value: 60,
      },
      {
        property: 'perception',
        value: 80,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: 10,
      },
    ],
  },
  {
    id: '566',
    name: 'Gun A 317/Gun A370',
    image:
      'https://wiki.dreadcast.net/images/thumb/0/01/A-317_REVOLVER_MAGNUS_BLEU_262-PX.png/90px-A-317_REVOLVER_MAGNUS_BLEU_262-PX.png',
    tech: 320,
    integrity: 300,
    type: '1handShot',
    minDamage: 6,
    maxDamage: 12,
    hitsPerRound: 2,
    hands: 1,
    reach: 4,
  },
  {
    id: '567',
    name: 'Fusil A 317 T',
    image:
      'https://wiki.dreadcast.net/images/thumb/4/4f/A-317_FUSIL_D_ASSAULT_GRIPPIN_ROUGE_262-PX.png/150px-A-317_FUSIL_D_ASSAULT_GRIPPIN_ROUGE_262-PX.png',
    tech: 470,
    integrity: 300,
    type: '2handsShot',
    minDamage: 24,
    maxDamage: 42,
    hitsPerRound: 1,
    hands: 2,
    reach: 12,
  },
  {
    id: '568',
    name: 'Fusil A 332',
    image:
      'https://wiki.dreadcast.net/images/thumb/b/be/A332WEAPON_PM_ROUGE.png/100px-A332WEAPON_PM_ROUGE.png',
    tech: 130,
    integrity: 350,
    type: '2handsShot',
    minDamage: 2,
    maxDamage: 14,
    hitsPerRound: 5,
    hands: 2,
    reach: 5,
  },
  {
    id: '569',
    name: 'Azmat',
    image:
      'https://wiki.dreadcast.net/images/thumb/a/a9/AZMAT262.png/150px-AZMAT262.png',
    tech: 320,
    integrity: 90,
    type: '1handShot',
    minDamage: 6,
    maxDamage: 12,
    hitsPerRound: 2,
    hands: 1,
    reach: 4,
  },
  {
    id: '570',
    name: 'Flingue plasma',
    image:
      'https://wiki.dreadcast.net/images/thumb/4/48/FLINGUE_PLASMA262.png/150px-FLINGUE_PLASMA262.png',
    tech: 550,
    integrity: 130,
    type: '1handShot',
    minDamage: 11,
    maxDamage: 21,
    hitsPerRound: 1,
    hands: 1,
    reach: 3,
  },
  {
    id: '571',
    name: 'Fusil laser',
    image:
      'https://wiki.dreadcast.net/images/thumb/f/ff/FUSIL_LASER2.png/150px-FUSIL_LASER2.png',
    tech: 470,
    integrity: 145,
    type: '2handsShot',
    minDamage: 24,
    maxDamage: 42,
    hitsPerRound: 1,
    hands: 2,
    reach: 12,
    prerequisites: [
      {
        property: 'perception',
        value: 150,
      },
    ],
  },
  {
    id: '572',
    name: 'Fusil plasma',
    image: 'https://wiki.dreadcast.net/images/9/90/Plasma.png',
    tech: 0,
    integrity: 85,
    type: '2handsShot',
    minDamage: 24,
    maxDamage: 40,
    hitsPerRound: 1,
    hands: 2,
    reach: 2,
    prerequisites: [
      {
        property: 'strength',
        value: 50,
      },
      {
        property: 'perception',
        value: 50,
      },
    ],
  },
  {
    id: '573',
    name: 'Gatling laser',
    image:
      'https://wiki.dreadcast.net/images/thumb/0/0c/Gatling_Laser2.png/150px-Gatling_Laser2.png',
    tech: 260,
    integrity: 100,
    type: '2handsShot',
    minDamage: 12,
    maxDamage: 22,
    hitsPerRound: 3,
    hands: 2,
    reach: 3,
    prerequisites: [
      {
        property: 'strength',
        value: 120,
      },
      {
        property: 'perception',
        value: 60,
      },
      {
        property: 'robustness',
        value: 100,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -10,
      },
      {
        property: 'perception',
        value: -35,
      },
    ],
  },
  {
    id: '574',
    name: 'Pulseur',
    image: 'https://wiki.dreadcast.net/images/8/84/Pulseur.png',
    tech: 340,
    integrity: 115,
    type: '1handShot',
    minDamage: 16,
    maxDamage: 26,
    hitsPerRound: 1,
    hands: 1,
    reach: 4,
    prerequisites: [
      {
        property: 'agility',
        value: 60,
      },
      {
        property: 'perception',
        value: 60,
      },
    ],
  },
  {
    id: '575',
    name: 'V42J4',
    image:
      'https://wiki.dreadcast.net/images/thumb/b/b6/V42J4_262px.png/150px-V42J4_262px.png',
    tech: 260,
    integrity: 120,
    type: '2handsShot',
    minDamage: 20,
    maxDamage: 26,
    hitsPerRound: 2,
    hands: 2,
    reach: 7,
    prerequisites: [
      {
        property: 'agility',
        value: 80,
      },
      {
        property: 'perception',
        value: 80,
      },
    ],
  },
  {
    id: '576',
    name: 'Runner',
    image:
      'https://wiki.dreadcast.net/images/thumb/5/5e/Runner_262.png/150px-Runner_262.png',
    tech: 320,
    integrity: 90,
    type: '1handShot',
    minDamage: 3,
    maxDamage: 15,
    hitsPerRound: 2,
    hands: 1,
    reach: 4,
    prerequisites: [
      {
        property: 'perception',
        value: 150,
      },
    ],
  },
  {
    id: '577',
    name: 'Canon Anti-matériel',
    image:
      'https://wiki.dreadcast.net/images/thumb/b/b8/Gatling_G1.png/150px-Gatling_G1.png',
    tech: 260,
    integrity: 100,
    type: '2handsShot',
    minDamage: 18,
    maxDamage: 42,
    hitsPerRound: 2,
    hands: 2,
    reach: 5,
    prerequisites: [
      {
        property: 'strength',
        value: 120,
      },
      {
        property: 'perception',
        value: 60,
      },
      {
        property: 'robustness',
        value: 100,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -10,
      },
      {
        property: 'perception',
        value: -35,
      },
    ],
  },
  {
    id: '578',
    name: 'Fusil Sniper Laser',
    image:
      'https://wiki.dreadcast.net/images/thumb/1/18/Fusilsniper.png/150px-Fusilsniper.png',
    tech: 470,
    integrity: 145,
    type: '2handsShot',
    minDamage: 36,
    maxDamage: 48,
    hitsPerRound: 1,
    hands: 2,
    reach: 14,
    prerequisites: [
      {
        property: 'perception',
        value: 150,
      },
    ],
  },
  {
    id: '579',
    name: 'F.I.S.T',
    image: 'https://wiki.dreadcast.net/images/a/aa/Fusil_iem.png',
    tech: 500,
    integrity: 130,
    type: '1handShot',
    minDamage: 13,
    maxDamage: 25,
    hitsPerRound: 1,
    hands: 1,
    reach: 6,
    effects: [
      {
        property: 'perception',
        value: 5,
      },
    ],
  },
  {
    id: '580',
    name: 'Lance-flammes',
    image:
      'https://wiki.dreadcast.net/images/thumb/3/3e/LANCE-FLAME2.png/150px-LANCE-FLAME2.png',
    tech: 0,
    integrity: 110,
    type: '2handsShot',
    minDamage: 12,
    maxDamage: 60,
    hitsPerRound: 2,
    hands: 2,
    reach: 4,
    prerequisites: [
      {
        property: 'strength',
        value: 80,
      },
      {
        property: 'robustness',
        value: 80,
      },
    ],
    effects: [
      {
        property: 'agility',
        value: -5,
      },
    ],
  },
  {
    id: '581',
    name: 'Arbalète automatique',
    image: 'https://wiki.dreadcast.net/images/b/b6/Arba-auto.png',
    tech: 320,
    integrity: 250,
    type: '1handShot',
    minDamage: 15,
    maxDamage: 25,
    hitsPerRound: 1,
    hands: 1,
    reach: 4,
    prerequisites: [
      {
        property: 'agility',
        value: 70,
      },
      {
        property: 'perception',
        value: 70,
      },
    ],
  },
  {
    id: '582',
    name: 'Arc électrique/Arc à positron',
    image:
      'https://wiki.dreadcast.net/images/thumb/c/c7/Arc_positrons.png/150px-Arc_positrons.png',
    tech: 450,
    integrity: 150,
    type: '2handsShot',
    minDamage: 20,
    maxDamage: 48,
    hitsPerRound: 1,
    hands: 2,
    reach: 9,
    prerequisites: [
      {
        property: 'agility',
        value: 180,
      },
      {
        property: 'perception',
        value: 100,
      },
    ],
    effects: [
      {
        property: 'perception',
        value: 5,
      },
    ],
  },
  {
    id: '583',
    name: 'Arc de contrôle/RedBow',
    image: 'https://wiki.dreadcast.net/images/7/7d/Arc_controle_bleu.png',
    tech: 460,
    integrity: 150,
    type: '2handsShot',
    minDamage: 22,
    maxDamage: 40,
    hitsPerRound: 1,
    hands: 2,
    reach: 12,
    prerequisites: [
      {
        property: 'agility',
        value: 120,
      },
      {
        property: 'perception',
        value: 150,
      },
    ],
  },
  {
    id: '584',
    name: 'Arc à poulie',
    image:
      'https://wiki.dreadcast.net/images/thumb/4/4a/Arc_a_poulie.png/150px-Arc_a_poulie.png',
    tech: 450,
    integrity: 180,
    type: '2handsShot',
    minDamage: 18,
    maxDamage: 48,
    hitsPerRound: 1,
    hands: 2,
    reach: 9,
    prerequisites: [
      {
        property: 'agility',
        value: 120,
      },
      {
        property: 'perception',
        value: 120,
      },
    ],
  },
  {
    id: '585',
    name: 'Pistaclou',
    image:
      'https://wiki.dreadcast.net/images/thumb/2/21/PISTACLOUS262.png/150px-PISTACLOUS262.png',
    tech: 80,
    integrity: 80,
    type: '1handShot',
    minDamage: 7,
    maxDamage: 13,
    hitsPerRound: 3,
    hands: 1,
    reach: 1,
  },
  {
    id: '586',
    name: 'Pistoconfetti',
    image: 'https://wiki.dreadcast.net/images/0/0d/Pistoconfetti.png',
    tech: 0,
    integrity: 1,
    type: '1handShot',
    minDamage: 0,
    maxDamage: 2,
    hitsPerRound: 1,
    hands: 1,
    reach: 1,
  },
  {
    id: '587',
    name: 'Pistolet à billes',
    image: 'https://wiki.dreadcast.net/images/1/1f/Pisto-bille.png',
    tech: 50,
    integrity: 200,
    type: '1handShot',
    minDamage: 2,
    maxDamage: 4,
    hitsPerRound: 1,
    hands: 1,
    reach: 1,
  },
  {
    id: '588',
    name: 'Pistolet à ventouses',
    image: 'https://wiki.dreadcast.net/images/6/67/Pisto-ventouse.png',
    tech: 0,
    integrity: 120,
    type: '1handShot',
    minDamage: 0,
    maxDamage: 2,
    hitsPerRound: 1,
    hands: 1,
    reach: 1,
  },
  {
    id: '589',
    name: 'Railgun',
    image:
      'https://wiki.dreadcast.net/images/thumb/c/c6/RAIL-GUN262.png/150px-RAIL-GUN262.png',
    tech: 260,
    integrity: 60,
    type: '2handsShot',
    minDamage: 10,
    maxDamage: 70,
    hitsPerRound: 1,
    hands: 2,
    reach: 10,
  },
  {
    id: '590',
    name: 'Vibrolame',
    image:
      'https://wiki.dreadcast.net/images/thumb/2/2e/Vibrolame.png/100px-Vibrolame.png',
    tech: 360,
    integrity: 150,
    type: '1handShot',
    minDamage: 20,
    maxDamage: 36,
    hitsPerRound: 1,
    hands: 1,
    reach: 0,
    prerequisites: [
      {
        property: 'agility',
        value: 110,
      },
    ],
  },
];
