import { createRepositoryErrorClass } from '@/utils/repository-error';

export const SUBSCRIPTION_REPOSITORY_ERROR_CODE = {
  MISSING_AUTH_SESSION: 'MISSING_AUTH_SESSION',
  FETCH_SUBSCRIPTIONS_FAILED: 'FETCH_SUBSCRIPTIONS_FAILED',
  FETCH_SUBSCRIPTION_PLANS_FAILED: 'FETCH_SUBSCRIPTION_PLANS_FAILED',
  CREATE_SUBSCRIPTION_FAILED: 'CREATE_SUBSCRIPTION_FAILED',
  INVALID_SUBSCRIPTIONS_PAYLOAD: 'INVALID_SUBSCRIPTIONS_PAYLOAD',
  INVALID_SUBSCRIPTION_PLANS_PAYLOAD: 'INVALID_SUBSCRIPTION_PLANS_PAYLOAD',
  INVALID_SUBSCRIPTION_PAYLOAD: 'INVALID_SUBSCRIPTION_PAYLOAD',
} as const;

export const SubscriptionRepositoryError = createRepositoryErrorClass(
  'SubscriptionRepositoryError',
);
