// Generated by the Supabase MCP (generate_typescript_types) — do not edit.
// Regenerate after each migration touching the public schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      build: {
        Row: {
          created_at: string | null
          id: string
          saved_at: string
          snapshot: Json
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          saved_at?: string
          snapshot: Json
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          saved_at?: string
          snapshot?: Json
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      community_build: {
        Row: {
          author_id: string
          content_updated_at: string
          description: string | null
          detected_specialization: string
          game_version: string
          gender: string
          has_heal_weapon: boolean
          id: string
          key_stats: Json
          published_at: string
          race: Database["public"]["Enums"]["race_type"]
          rating_avg: number | null
          rating_count: number
          rating_sum: number
          source_build_id: string | null
          specialization: string
          title: string
          updated_at: string
          weapon_types: Database["public"]["Enums"]["item_type"][]
        }
        Insert: {
          author_id: string
          content_updated_at?: string
          description?: string | null
          detected_specialization: string
          game_version: string
          gender: string
          has_heal_weapon?: boolean
          id?: string
          key_stats?: Json
          published_at?: string
          race: Database["public"]["Enums"]["race_type"]
          rating_avg?: number | null
          rating_count?: number
          rating_sum?: number
          source_build_id?: string | null
          specialization: string
          title: string
          updated_at?: string
          weapon_types?: Database["public"]["Enums"]["item_type"][]
        }
        Update: {
          author_id?: string
          content_updated_at?: string
          description?: string | null
          detected_specialization?: string
          game_version?: string
          gender?: string
          has_heal_weapon?: boolean
          id?: string
          key_stats?: Json
          published_at?: string
          race?: Database["public"]["Enums"]["race_type"]
          rating_avg?: number | null
          rating_count?: number
          rating_sum?: number
          source_build_id?: string | null
          specialization?: string
          title?: string
          updated_at?: string
          weapon_types?: Database["public"]["Enums"]["item_type"][]
        }
        Relationships: [
          {
            foreignKeyName: "community_build_game_version_fkey"
            columns: ["game_version"]
            isOneToOne: false
            referencedRelation: "game_version"
            referencedColumns: ["code"]
          },
          {
            foreignKeyName: "community_build_source_build_id_fkey"
            columns: ["source_build_id"]
            isOneToOne: true
            referencedRelation: "build"
            referencedColumns: ["id"]
          },
        ]
      }
      community_build_content: {
        Row: {
          author_id: string
          drug_id: string | null
          implant_names: string[]
          item_ids: string[]
          kit_ids: string[]
          publication_id: string
          snapshot: Json
          stat_vec: number[]
          stats: Json
        }
        Insert: {
          author_id: string
          drug_id?: string | null
          implant_names?: string[]
          item_ids?: string[]
          kit_ids?: string[]
          publication_id: string
          snapshot: Json
          stat_vec: number[]
          stats: Json
        }
        Update: {
          author_id?: string
          drug_id?: string | null
          implant_names?: string[]
          item_ids?: string[]
          kit_ids?: string[]
          publication_id?: string
          snapshot?: Json
          stat_vec?: number[]
          stats?: Json
        }
        Relationships: [
          {
            foreignKeyName: "community_build_content_publication_id_fkey"
            columns: ["publication_id"]
            isOneToOne: true
            referencedRelation: "community_build"
            referencedColumns: ["id"]
          },
        ]
      }
      community_favorite: {
        Row: {
          created_at: string
          publication_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          publication_id: string
          user_id?: string
        }
        Update: {
          created_at?: string
          publication_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "community_favorite_publication_id_fkey"
            columns: ["publication_id"]
            isOneToOne: false
            referencedRelation: "community_build"
            referencedColumns: ["id"]
          },
        ]
      }
      community_review: {
        Row: {
          body: string | null
          created_at: string
          id: string
          publication_id: string
          reviewer_id: string
          stars: number
          updated_at: string
        }
        Insert: {
          body?: string | null
          created_at?: string
          id?: string
          publication_id: string
          reviewer_id?: string
          stars: number
          updated_at?: string
        }
        Update: {
          body?: string | null
          created_at?: string
          id?: string
          publication_id?: string
          reviewer_id?: string
          stars?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "community_review_publication_id_fkey"
            columns: ["publication_id"]
            isOneToOne: false
            referencedRelation: "community_build"
            referencedColumns: ["id"]
          },
        ]
      }
      drug: {
        Row: {
          created_at: string | null
          id: string
          image: string
          name: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          id: string
          image: string
          name: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          image?: string
          name?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      game_version: {
        Row: {
          code: string
          created_at: string
          is_current: boolean
          label: string
          released_at: string | null
        }
        Insert: {
          code: string
          created_at?: string
          is_current?: boolean
          label: string
          released_at?: string | null
        }
        Update: {
          code?: string
          created_at?: string
          is_current?: boolean
          label?: string
          released_at?: string | null
        }
        Relationships: []
      }
      implant: {
        Row: {
          created_at: string | null
          id: number
          level_max: number
          name: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          id: number
          level_max: number
          name: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          id?: number
          level_max?: number
          name?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      implant_attribute: {
        Row: {
          attribute: Database["public"]["Enums"]["stat_property"]
          created_at: string | null
          id: string
          implant_id: number
        }
        Insert: {
          attribute: Database["public"]["Enums"]["stat_property"]
          created_at?: string | null
          id?: string
          implant_id: number
        }
        Update: {
          attribute?: Database["public"]["Enums"]["stat_property"]
          created_at?: string | null
          id?: string
          implant_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "implant_attribute_implant_id_fkey"
            columns: ["implant_id"]
            isOneToOne: false
            referencedRelation: "implant"
            referencedColumns: ["id"]
          },
        ]
      }
      implant_value: {
        Row: {
          created_at: string | null
          id: string
          implant_id: number
          level: number
          value: number
        }
        Insert: {
          created_at?: string | null
          id?: string
          implant_id: number
          level: number
          value: number
        }
        Update: {
          created_at?: string | null
          id?: string
          implant_id?: number
          level?: number
          value?: number
        }
        Relationships: [
          {
            foreignKeyName: "implant_value_implant_id_fkey"
            columns: ["implant_id"]
            isOneToOne: false
            referencedRelation: "implant"
            referencedColumns: ["id"]
          },
        ]
      }
      item: {
        Row: {
          created_at: string | null
          damage_bonus: number | null
          hands: number | null
          hits_per_round: number | null
          id: string
          image: string
          integrity: number
          max_damage: number | null
          max_heal: number | null
          min_damage: number | null
          min_heal: number | null
          name: string
          reach: number | null
          tech: number
          type: Database["public"]["Enums"]["item_type"]
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          damage_bonus?: number | null
          hands?: number | null
          hits_per_round?: number | null
          id: string
          image: string
          integrity: number
          max_damage?: number | null
          max_heal?: number | null
          min_damage?: number | null
          min_heal?: number | null
          name: string
          reach?: number | null
          tech: number
          type: Database["public"]["Enums"]["item_type"]
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          damage_bonus?: number | null
          hands?: number | null
          hits_per_round?: number | null
          id?: string
          image?: string
          integrity?: number
          max_damage?: number | null
          max_heal?: number | null
          min_damage?: number | null
          min_heal?: number | null
          name?: string
          reach?: number | null
          tech?: number
          type?: Database["public"]["Enums"]["item_type"]
          updated_at?: string | null
        }
        Relationships: []
      }
      item_effect: {
        Row: {
          created_at: string | null
          id: string
          item_id: string
          property: Database["public"]["Enums"]["stat_property"]
          value: number
        }
        Insert: {
          created_at?: string | null
          id?: string
          item_id: string
          property: Database["public"]["Enums"]["stat_property"]
          value: number
        }
        Update: {
          created_at?: string | null
          id?: string
          item_id?: string
          property?: Database["public"]["Enums"]["stat_property"]
          value?: number
        }
        Relationships: [
          {
            foreignKeyName: "item_effect_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "item"
            referencedColumns: ["id"]
          },
        ]
      }
      item_prerequisite: {
        Row: {
          created_at: string | null
          id: string
          item_id: string
          property: Database["public"]["Enums"]["stat_property"]
          value: number
        }
        Insert: {
          created_at?: string | null
          id?: string
          item_id: string
          property: Database["public"]["Enums"]["stat_property"]
          value: number
        }
        Update: {
          created_at?: string | null
          id?: string
          item_id?: string
          property?: Database["public"]["Enums"]["stat_property"]
          value?: number
        }
        Relationships: [
          {
            foreignKeyName: "item_prerequisite_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "item"
            referencedColumns: ["id"]
          },
        ]
      }
      item_prerequisite_implant: {
        Row: {
          created_at: string | null
          implant_id: number
          item_id: string
        }
        Insert: {
          created_at?: string | null
          implant_id: number
          item_id: string
        }
        Update: {
          created_at?: string | null
          implant_id?: number
          item_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "item_prerequisite_implant_implant_id_fkey"
            columns: ["implant_id"]
            isOneToOne: false
            referencedRelation: "implant"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "item_prerequisite_implant_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "item"
            referencedColumns: ["id"]
          },
        ]
      }
      item_prerequisite_race: {
        Row: {
          created_at: string | null
          item_id: string
          race: Database["public"]["Enums"]["race_type"]
        }
        Insert: {
          created_at?: string | null
          item_id: string
          race: Database["public"]["Enums"]["race_type"]
        }
        Update: {
          created_at?: string | null
          item_id?: string
          race?: Database["public"]["Enums"]["race_type"]
        }
        Relationships: [
          {
            foreignKeyName: "item_prerequisite_race_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "item"
            referencedColumns: ["id"]
          },
        ]
      }
      item_prerequisite_title: {
        Row: {
          created_at: string | null
          item_id: string
          title_id: string
        }
        Insert: {
          created_at?: string | null
          item_id: string
          title_id: string
        }
        Update: {
          created_at?: string | null
          item_id?: string
          title_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "item_prerequisite_title_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "item"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "item_prerequisite_title_title_id_fkey"
            columns: ["title_id"]
            isOneToOne: false
            referencedRelation: "title"
            referencedColumns: ["id"]
          },
        ]
      }
      kit: {
        Row: {
          created_at: string | null
          id: string
          name: string
          tech: number
          type: Database["public"]["Enums"]["item_type"]
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          id: string
          name: string
          tech: number
          type: Database["public"]["Enums"]["item_type"]
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          name?: string
          tech?: number
          type?: Database["public"]["Enums"]["item_type"]
          updated_at?: string | null
        }
        Relationships: []
      }
      kit_effect: {
        Row: {
          created_at: string | null
          id: string
          kit_id: string
          property: Database["public"]["Enums"]["stat_property"]
          value: number
        }
        Insert: {
          created_at?: string | null
          id?: string
          kit_id: string
          property: Database["public"]["Enums"]["stat_property"]
          value: number
        }
        Update: {
          created_at?: string | null
          id?: string
          kit_id?: string
          property?: Database["public"]["Enums"]["stat_property"]
          value?: number
        }
        Relationships: [
          {
            foreignKeyName: "kit_effect_kit_id_fkey"
            columns: ["kit_id"]
            isOneToOne: false
            referencedRelation: "kit"
            referencedColumns: ["id"]
          },
        ]
      }
      kit_prerequisite: {
        Row: {
          created_at: string | null
          id: string
          kit_id: string
          property: Database["public"]["Enums"]["stat_property"]
          value: number
        }
        Insert: {
          created_at?: string | null
          id?: string
          kit_id: string
          property: Database["public"]["Enums"]["stat_property"]
          value: number
        }
        Update: {
          created_at?: string | null
          id?: string
          kit_id?: string
          property?: Database["public"]["Enums"]["stat_property"]
          value?: number
        }
        Relationships: [
          {
            foreignKeyName: "kit_prerequisite_kit_id_fkey"
            columns: ["kit_id"]
            isOneToOne: false
            referencedRelation: "kit"
            referencedColumns: ["id"]
          },
        ]
      }
      kit_prerequisite_implant: {
        Row: {
          created_at: string | null
          implant_id: number
          kit_id: string
        }
        Insert: {
          created_at?: string | null
          implant_id: number
          kit_id: string
        }
        Update: {
          created_at?: string | null
          implant_id?: number
          kit_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "kit_prerequisite_implant_implant_id_fkey"
            columns: ["implant_id"]
            isOneToOne: false
            referencedRelation: "implant"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kit_prerequisite_implant_kit_id_fkey"
            columns: ["kit_id"]
            isOneToOne: false
            referencedRelation: "kit"
            referencedColumns: ["id"]
          },
        ]
      }
      kit_prerequisite_race: {
        Row: {
          created_at: string | null
          kit_id: string
          race: Database["public"]["Enums"]["race_type"]
        }
        Insert: {
          created_at?: string | null
          kit_id: string
          race: Database["public"]["Enums"]["race_type"]
        }
        Update: {
          created_at?: string | null
          kit_id?: string
          race?: Database["public"]["Enums"]["race_type"]
        }
        Relationships: [
          {
            foreignKeyName: "kit_prerequisite_race_kit_id_fkey"
            columns: ["kit_id"]
            isOneToOne: false
            referencedRelation: "kit"
            referencedColumns: ["id"]
          },
        ]
      }
      kit_prerequisite_title: {
        Row: {
          created_at: string | null
          kit_id: string
          title_id: string
        }
        Insert: {
          created_at?: string | null
          kit_id: string
          title_id: string
        }
        Update: {
          created_at?: string | null
          kit_id?: string
          title_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "kit_prerequisite_title_kit_id_fkey"
            columns: ["kit_id"]
            isOneToOne: false
            referencedRelation: "kit"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kit_prerequisite_title_title_id_fkey"
            columns: ["title_id"]
            isOneToOne: false
            referencedRelation: "title"
            referencedColumns: ["id"]
          },
        ]
      }
      race: {
        Row: {
          agility: number
          computing: number
          created_at: string | null
          engineering: number
          health: number
          medicine: number
          perception: number
          robustness: number
          stamina: number
          stealth: number
          strength: number
          type: Database["public"]["Enums"]["race_type"]
          updated_at: string | null
        }
        Insert: {
          agility?: number
          computing?: number
          created_at?: string | null
          engineering?: number
          health?: number
          medicine?: number
          perception?: number
          robustness?: number
          stamina?: number
          stealth?: number
          strength?: number
          type: Database["public"]["Enums"]["race_type"]
          updated_at?: string | null
        }
        Update: {
          agility?: number
          computing?: number
          created_at?: string | null
          engineering?: number
          health?: number
          medicine?: number
          perception?: number
          robustness?: number
          stamina?: number
          stealth?: number
          strength?: number
          type?: Database["public"]["Enums"]["race_type"]
          updated_at?: string | null
        }
        Relationships: []
      }
      stat_modifier: {
        Row: {
          created_at: string | null
          drug_id: string
          id: string
          property: Database["public"]["Enums"]["stat_property"]
          value: number
        }
        Insert: {
          created_at?: string | null
          drug_id: string
          id?: string
          property: Database["public"]["Enums"]["stat_property"]
          value: number
        }
        Update: {
          created_at?: string | null
          drug_id?: string
          id?: string
          property?: Database["public"]["Enums"]["stat_property"]
          value?: number
        }
        Relationships: [
          {
            foreignKeyName: "stat_modifier_drug_id_fkey"
            columns: ["drug_id"]
            isOneToOne: false
            referencedRelation: "drug"
            referencedColumns: ["id"]
          },
        ]
      }
      subscription: {
        Row: {
          created_at: string | null
          ends_at: string
          id: string
          plan_code: string
          plan_name: string
          price_cents: number
          starts_at: string
          status: string
          updated_at: string | null
          user_id: string
          validated_at: string | null
          validated_by: string | null
        }
        Insert: {
          created_at?: string | null
          ends_at: string
          id?: string
          plan_code: string
          plan_name: string
          price_cents: number
          starts_at: string
          status?: string
          updated_at?: string | null
          user_id: string
          validated_at?: string | null
          validated_by?: string | null
        }
        Update: {
          created_at?: string | null
          ends_at?: string
          id?: string
          plan_code?: string
          plan_name?: string
          price_cents?: number
          starts_at?: string
          status?: string
          updated_at?: string | null
          user_id?: string
          validated_at?: string | null
          validated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "subscription_plan_code_fk"
            columns: ["plan_code"]
            isOneToOne: false
            referencedRelation: "subscription_plan"
            referencedColumns: ["code"]
          },
        ]
      }
      subscription_plan: {
        Row: {
          code: string
          created_at: string | null
          duration_ingame_years: number | null
          is_active: boolean
          label: string
          price_cents: number
          sort_order: number
          updated_at: string | null
        }
        Insert: {
          code: string
          created_at?: string | null
          duration_ingame_years?: number | null
          is_active?: boolean
          label: string
          price_cents: number
          sort_order: number
          updated_at?: string | null
        }
        Update: {
          code?: string
          created_at?: string | null
          duration_ingame_years?: number | null
          is_active?: boolean
          label?: string
          price_cents?: number
          sort_order?: number
          updated_at?: string | null
        }
        Relationships: []
      }
      title: {
        Row: {
          created_at: string | null
          id: string
          name: string
        }
        Insert: {
          created_at?: string | null
          id: string
          name: string
        }
        Update: {
          created_at?: string | null
          id?: string
          name?: string
        }
        Relationships: []
      }
      user_profile: {
        Row: {
          created_at: string
          pseudo: string
          user_id: string
        }
        Insert: {
          created_at?: string
          pseudo: string
          user_id?: string
        }
        Update: {
          created_at?: string
          pseudo?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      community_for_you: {
        Args: { p_limit?: number }
        Returns: {
          publication_id: string
          similarity: number
        }[]
      }
      community_get_preview: {
        Args: { p_id: string }
        Returns: {
          author_pseudo: string
          content_updated_at: string
          description: string
          detected_specialization: string
          game_version: string
          gender: string
          has_heal_weapon: boolean
          id: string
          key_stats: Json
          published_at: string
          race: Database["public"]["Enums"]["race_type"]
          rating_avg: number
          rating_count: number
          specialization: string
          title: string
          weapon_types: Database["public"]["Enums"]["item_type"][]
        }[]
      }
      community_publish: {
        Args: {
          p_description: string
          p_detected_specialization: string
          p_slot: number
          p_specialization: string
          p_stats: Json
          p_title: string
        }
        Returns: string
      }
      community_search: {
        Args: {
          p_author_id?: string
          p_drug_ids?: string[]
          p_favorites_only?: boolean
          p_game_version?: string
          p_genders?: string[]
          p_heal_only?: boolean
          p_ids?: string[]
          p_implants?: string[]
          p_item_ids?: string[]
          p_limit?: number
          p_min_rating?: number
          p_offset?: number
          p_query?: string
          p_races?: Database["public"]["Enums"]["race_type"][]
          p_sort?: string
          p_specializations?: string[]
          p_stat_min?: Json
          p_weapon_types?: Database["public"]["Enums"]["item_type"][]
        }
        Returns: {
          author_id: string
          author_pseudo: string
          bayes_score: number
          content_updated_at: string
          description: string
          detected_specialization: string
          game_version: string
          gender: string
          has_heal_weapon: boolean
          id: string
          is_favorite: boolean
          is_mine: boolean
          key_stats: Json
          published_at: string
          race: Database["public"]["Enums"]["race_type"]
          rating_avg: number
          rating_count: number
          specialization: string
          stats: Json
          title: string
          total_count: number
          trend_score: number
          weapon_types: Database["public"]["Enums"]["item_type"][]
        }[]
      }
      community_similar: {
        Args: {
          p_exclude_ids?: string[]
          p_game_version?: string
          p_limit?: number
          p_stats: Json
        }
        Returns: {
          publication_id: string
          similarity: number
        }[]
      }
      community_update_publication: {
        Args: {
          p_description: string
          p_detected_specialization?: string
          p_id: string
          p_refresh: boolean
          p_specialization: string
          p_stats?: Json
          p_title: string
        }
        Returns: undefined
      }
    }
    Enums: {
      item_type:
        | "head"
        | "chest"
        | "legs"
        | "feet"
        | "secondary"
        | "1handShot"
        | "2handsShot"
        | "1handMelee"
        | "2handsMelee"
      race_type:
        | "Humain"
        | "Elfe"
        | "Nain"
        | "Orc"
        | "Troll"
        | "Outrilien"
        | "Vautour"
        | "Gobelin"
        | "Kobold"
        | "Gnoll"
        | "Androide"
      stat_property:
        | "strength"
        | "agility"
        | "robustness"
        | "perception"
        | "stealth"
        | "computing"
        | "medicine"
        | "engineering"
        | "health"
        | "stamina"
        | "integrity"
        | "speed"
        | "raceDamage"
        | "hitRating"
        | "teamHeal"
        | "cacDamage"
        | "criticalCacChance"
        | "criticalCacDamage"
        | "hitDamages"
        | "criticalHitDamage"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      item_type: [
        "head",
        "chest",
        "legs",
        "feet",
        "secondary",
        "1handShot",
        "2handsShot",
        "1handMelee",
        "2handsMelee",
      ],
      race_type: [
        "Humain",
        "Elfe",
        "Nain",
        "Orc",
        "Troll",
        "Outrilien",
        "Vautour",
        "Gobelin",
        "Kobold",
        "Gnoll",
        "Androide",
      ],
      stat_property: [
        "strength",
        "agility",
        "robustness",
        "perception",
        "stealth",
        "computing",
        "medicine",
        "engineering",
        "health",
        "stamina",
        "integrity",
        "speed",
        "raceDamage",
        "hitRating",
        "teamHeal",
        "cacDamage",
        "criticalCacChance",
        "criticalCacDamage",
        "hitDamages",
        "criticalHitDamage",
      ],
    },
  },
} as const
