/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AbonnementRouteImport } from './routes/abonnement'
import { Route as IndexRouteImport } from './routes/index'

const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementRoute = AbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/connexion': typeof ConnexionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/connexion': typeof ConnexionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/connexion': typeof ConnexionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/abonnement' | '/connexion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/abonnement' | '/connexion'
  id: '__root__' | '/' | '/abonnement' | '/connexion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementRoute: typeof AbonnementRoute
  ConnexionRoute: typeof ConnexionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnement': {
      id: '/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AbonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementRoute: AbonnementRoute,
  ConnexionRoute: ConnexionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
