/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as ConnectionRouteImport } from './routes/connection'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunauteIndexRouteImport } from './routes/communaute.index'
import { Route as SharedIdRouteImport } from './routes/shared.$id'
import { Route as CommunauteIdRouteImport } from './routes/communaute.$id'

const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionRoute = ConnectionRouteImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunauteIndexRoute = CommunauteIndexRouteImport.update({
  id: '/communaute/',
  path: '/communaute/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedIdRoute = SharedIdRouteImport.update({
  id: '/shared/$id',
  path: '/shared/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunauteIdRoute = CommunauteIdRouteImport.update({
  id: '/communaute/$id',
  path: '/communaute/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connection': typeof ConnectionRoute
  '/subscription': typeof SubscriptionRoute
  '/communaute/$id': typeof CommunauteIdRoute
  '/shared/$id': typeof SharedIdRoute
  '/communaute/': typeof CommunauteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connection': typeof ConnectionRoute
  '/subscription': typeof SubscriptionRoute
  '/communaute/$id': typeof CommunauteIdRoute
  '/shared/$id': typeof SharedIdRoute
  '/communaute': typeof CommunauteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connection': typeof ConnectionRoute
  '/subscription': typeof SubscriptionRoute
  '/communaute/$id': typeof CommunauteIdRoute
  '/shared/$id': typeof SharedIdRoute
  '/communaute/': typeof CommunauteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connection'
    | '/subscription'
    | '/communaute/$id'
    | '/shared/$id'
    | '/communaute/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connection'
    | '/subscription'
    | '/communaute/$id'
    | '/shared/$id'
    | '/communaute'
  id:
    | '__root__'
    | '/'
    | '/connection'
    | '/subscription'
    | '/communaute/$id'
    | '/shared/$id'
    | '/communaute/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionRoute: typeof ConnectionRoute
  SubscriptionRoute: typeof SubscriptionRoute
  CommunauteIdRoute: typeof CommunauteIdRoute
  SharedIdRoute: typeof SharedIdRoute
  CommunauteIndexRoute: typeof CommunauteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection': {
      id: '/connection'
      path: '/connection'
      fullPath: '/connection'
      preLoaderRoute: typeof ConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communaute/': {
      id: '/communaute/'
      path: '/communaute'
      fullPath: '/communaute/'
      preLoaderRoute: typeof CommunauteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$id': {
      id: '/shared/$id'
      path: '/shared/$id'
      fullPath: '/shared/$id'
      preLoaderRoute: typeof SharedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communaute/$id': {
      id: '/communaute/$id'
      path: '/communaute/$id'
      fullPath: '/communaute/$id'
      preLoaderRoute: typeof CommunauteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionRoute: ConnectionRoute,
  SubscriptionRoute: SubscriptionRoute,
  CommunauteIdRoute: CommunauteIdRoute,
  SharedIdRoute: SharedIdRoute,
  CommunauteIndexRoute: CommunauteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
