-- Seed data pour les kits de type chest

-- Insertion des kits
INSERT INTO kit (id, name, tech, type) VALUES
  ('0', 'Du Coach', 200, 'chest'::item_type),
  ('1', 'À capuchon', 80, 'chest'::item_type),
  ('2', 'Androïde', 0, 'chest'::item_type),
  ('3', 'Bien ajusté', 200, 'chest'::item_type),
  ('4', 'Blindé', 250, 'chest'::item_type),
  ('5', 'Chirurgien', 160, 'chest'::item_type),
  ('6', 'Combat', 70, 'chest'::item_type),
  ('7', 'Concepteur', 180, 'chest'::item_type),
  ('8', 'Decker', 110, 'chest'::item_type),
  ('9', 'Délégué Impérial', 330, 'chest'::item_type),
  ('10', 'Des anciens', 140, 'chest'::item_type),
  ('11', 'Doc', 120, 'chest'::item_type),
  ('12', 'Elfique', 160, 'chest'::item_type),
  ('13', 'Eugéniste', 200, 'chest'::item_type),
  ('14', 'Gnoll', 0, 'chest'::item_type),
  ('15', 'Gobelin', 0, 'chest'::item_type),
  ('16', 'Haut Dignitaire', 320, 'chest'::item_type),
  ('17', 'Impérial', 280, 'chest'::item_type),
  ('18', 'Ingénieur', 110, 'chest'::item_type),
  ('19', 'Journaliste', 280, 'chest'::item_type),
  ('20', 'Kobold', 180, 'chest'::item_type),
  ('21', 'Loyaliste', 90, 'chest'::item_type),
  ('22', 'Nain', 0, 'chest'::item_type),
  ('23', 'Orc', 160, 'chest'::item_type),
  ('24', 'Outrilien', 0, 'chest'::item_type),
  ('25', 'Police', 150, 'chest'::item_type),
  ('26', 'Souple', 90, 'chest'::item_type),
  ('27', 'Troll', 340, 'chest'::item_type),
  ('28', 'Vautour', 0, 'chest'::item_type),
  ('29', 'Noble', 220, 'chest'::item_type),
  ('30', 'Paria', 120, 'chest'::item_type),
  ('31', 'Matriciel', 160, 'chest'::item_type)
ON CONFLICT (id) DO NOTHING;

-- Insertion des effets
INSERT INTO kit_effect (kit_id, property, value) VALUES
  ('0', 'agility'::stat_property, -20),
  ('0', 'stealth'::stat_property, -20),
  ('1', 'stealth'::stat_property, 6),
  ('2', 'stamina'::stat_property, 20),
  ('3', 'strength'::stat_property, 5),
  ('3', 'agility'::stat_property, 15),
  ('3', 'robustness'::stat_property, -5),
  ('3', 'perception'::stat_property, 5),
  ('4', 'robustness'::stat_property, 16),
  ('5', 'medicine'::stat_property, 12),
  ('6', 'strength'::stat_property, 4),
  ('6', 'agility'::stat_property, -2),
  ('6', 'robustness'::stat_property, 4),
  ('7', 'stamina'::stat_property, 20),
  ('7', 'engineering'::stat_property, 16),
  ('8', 'computing'::stat_property, 9),
  ('9', 'agility'::stat_property, 12),
  ('9', 'robustness'::stat_property, 12),
  ('9', 'perception'::stat_property, 12),
  ('10', 'health'::stat_property, 6),
  ('10', 'agility'::stat_property, -2),
  ('10', 'robustness'::stat_property, 10),
  ('11', 'medicine'::stat_property, 7),
  ('11', 'stamina'::stat_property, 6),
  ('12', 'agility'::stat_property, 3),
  ('12', 'robustness'::stat_property, -3),
  ('12', 'perception'::stat_property, 17),
  ('13', 'strength'::stat_property, 8),
  ('13', 'agility'::stat_property, 8),
  ('13', 'robustness'::stat_property, 8),
  ('13', 'perception'::stat_property, 8),
  ('13', 'stealth'::stat_property, 8),
  ('13', 'computing'::stat_property, 8),
  ('13', 'medicine'::stat_property, 8),
  ('13', 'engineering'::stat_property, 8),
  ('14', 'agility'::stat_property, 4),
  ('15', 'engineering'::stat_property, 4),
  ('16', 'robustness'::stat_property, 4),
  ('16', 'perception'::stat_property, 14),
  ('16', 'medicine'::stat_property, 14),
  ('16', 'health'::stat_property, 12),
  ('17', 'robustness'::stat_property, 10),
  ('17', 'perception'::stat_property, 10),
  ('17', 'health'::stat_property, 8),
  ('18', 'engineering'::stat_property, 8),
  ('19', 'agility'::stat_property, -5),
  ('19', 'robustness'::stat_property, 5),
  ('19', 'perception'::stat_property, 10),
  ('19', 'health'::stat_property, 20),
  ('20', 'agility'::stat_property, 5),
  ('20', 'robustness'::stat_property, -8),
  ('20', 'stealth'::stat_property, 18),
  ('21', 'strength'::stat_property, 8),
  ('21', 'agility'::stat_property, 2),
  ('21', 'robustness'::stat_property, -2),
  ('22', 'health'::stat_property, 20),
  ('23', 'strength'::stat_property, 17),
  ('23', 'robustness'::stat_property, 2),
  ('24', 'medicine'::stat_property, 4),
  ('25', 'agility'::stat_property, 5),
  ('25', 'robustness'::stat_property, 10),
  ('25', 'stealth'::stat_property, -5),
  ('26', 'agility'::stat_property, 10),
  ('26', 'robustness'::stat_property, -2),
  ('27', 'robustness'::stat_property, 30),
  ('28', 'computing'::stat_property, 4),
  ('29', 'agility'::stat_property, 14),
  ('29', 'robustness'::stat_property, -5),
  ('29', 'perception'::stat_property, 14),
  ('29', 'stealth'::stat_property, -5),
  ('30', 'robustness'::stat_property, -10),
  ('30', 'computing'::stat_property, 10),
  ('30', 'health'::stat_property, 5),
  ('30', 'stamina'::stat_property, 5),
  ('31', 'computing'::stat_property, 13)
ON CONFLICT DO NOTHING;